/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.learning.activity.p2p.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.ted.lms.learning.activity.p2p.model.P2PActivity;
import com.ted.lms.learning.activity.p2p.model.P2PActivityModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the P2PActivity service. Represents a row in the &quot;PTP_P2PActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link P2PActivityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link P2PActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see P2PActivityImpl
 * @see P2PActivity
 * @see P2PActivityModel
 * @generated
 */
@ProviderType
public class P2PActivityModelImpl extends BaseModelImpl<P2PActivity>
	implements P2PActivityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p2p activity model instance should use the {@link P2PActivity} interface instead.
	 */
	public static final String TABLE_NAME = "PTP_P2PActivity";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "p2pActivityId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userCreateId", Types.BIGINT },
			{ "userCreateName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "actId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "countCorrections", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "date_", Types.TIMESTAMP },
			{ "asignationsCompleted", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("p2pActivityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userCreateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userCreateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("actId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("countCorrections", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("asignationsCompleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table PTP_P2PActivity (uuid_ VARCHAR(75) null,p2pActivityId LONG not null primary key,groupId LONG,companyId LONG,userCreateId LONG,userCreateName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,actId LONG,userId LONG,fileEntryId LONG,countCorrections LONG,description VARCHAR(75) null,date_ DATE null,asignationsCompleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table PTP_P2PActivity";
	public static final String ORDER_BY_JPQL = " ORDER BY p2pActivity.countCorrections ASC, p2pActivity.p2pActivityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PTP_P2PActivity.countCorrections ASC, PTP_P2PActivity.p2pActivityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ted.lms.learning.activity.p2p.model.P2PActivity"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ted.lms.learning.activity.p2p.model.P2PActivity"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ted.lms.learning.activity.p2p.model.P2PActivity"),
			true);
	public static final long ACTID_COLUMN_BITMASK = 1L;
	public static final long ASIGNATIONSCOMPLETED_COLUMN_BITMASK = 2L;
	public static final long COMPANYID_COLUMN_BITMASK = 4L;
	public static final long GROUPID_COLUMN_BITMASK = 8L;
	public static final long USERID_COLUMN_BITMASK = 16L;
	public static final long UUID_COLUMN_BITMASK = 32L;
	public static final long COUNTCORRECTIONS_COLUMN_BITMASK = 64L;
	public static final long P2PACTIVITYID_COLUMN_BITMASK = 128L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"lock.expiration.time.com.ted.lms.learning.activity.p2p.model.P2PActivity"));

	public P2PActivityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _p2pActivityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setP2pActivityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _p2pActivityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return P2PActivity.class;
	}

	@Override
	public String getModelClassName() {
		return P2PActivity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("p2pActivityId", getP2pActivityId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userCreateId", getUserCreateId());
		attributes.put("userCreateName", getUserCreateName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("actId", getActId());
		attributes.put("userId", getUserId());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("countCorrections", getCountCorrections());
		attributes.put("description", getDescription());
		attributes.put("date", getDate());
		attributes.put("asignationsCompleted", isAsignationsCompleted());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long p2pActivityId = (Long)attributes.get("p2pActivityId");

		if (p2pActivityId != null) {
			setP2pActivityId(p2pActivityId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userCreateId = (Long)attributes.get("userCreateId");

		if (userCreateId != null) {
			setUserCreateId(userCreateId);
		}

		String userCreateName = (String)attributes.get("userCreateName");

		if (userCreateName != null) {
			setUserCreateName(userCreateName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long actId = (Long)attributes.get("actId");

		if (actId != null) {
			setActId(actId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Long countCorrections = (Long)attributes.get("countCorrections");

		if (countCorrections != null) {
			setCountCorrections(countCorrections);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}

		Boolean asignationsCompleted = (Boolean)attributes.get(
				"asignationsCompleted");

		if (asignationsCompleted != null) {
			setAsignationsCompleted(asignationsCompleted);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getP2pActivityId() {
		return _p2pActivityId;
	}

	@Override
	public void setP2pActivityId(long p2pActivityId) {
		_columnBitmask = -1L;

		_p2pActivityId = p2pActivityId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserCreateId() {
		return _userCreateId;
	}

	@Override
	public void setUserCreateId(long userCreateId) {
		_userCreateId = userCreateId;
	}

	@Override
	public String getUserCreateName() {
		if (_userCreateName == null) {
			return "";
		}
		else {
			return _userCreateName;
		}
	}

	@Override
	public void setUserCreateName(String userCreateName) {
		_userCreateName = userCreateName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getActId() {
		return _actId;
	}

	@Override
	public void setActId(long actId) {
		_columnBitmask |= ACTID_COLUMN_BITMASK;

		if (!_setOriginalActId) {
			_setOriginalActId = true;

			_originalActId = _actId;
		}

		_actId = actId;
	}

	public long getOriginalActId() {
		return _originalActId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	@Override
	public long getCountCorrections() {
		return _countCorrections;
	}

	@Override
	public void setCountCorrections(long countCorrections) {
		_columnBitmask = -1L;

		_countCorrections = countCorrections;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_date = date;
	}

	@Override
	public boolean getAsignationsCompleted() {
		return _asignationsCompleted;
	}

	@Override
	public boolean isAsignationsCompleted() {
		return _asignationsCompleted;
	}

	@Override
	public void setAsignationsCompleted(boolean asignationsCompleted) {
		_columnBitmask |= ASIGNATIONSCOMPLETED_COLUMN_BITMASK;

		if (!_setOriginalAsignationsCompleted) {
			_setOriginalAsignationsCompleted = true;

			_originalAsignationsCompleted = _asignationsCompleted;
		}

		_asignationsCompleted = asignationsCompleted;
	}

	public boolean getOriginalAsignationsCompleted() {
		return _originalAsignationsCompleted;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				P2PActivity.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			P2PActivity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public P2PActivity toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (P2PActivity)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		P2PActivityImpl p2pActivityImpl = new P2PActivityImpl();

		p2pActivityImpl.setUuid(getUuid());
		p2pActivityImpl.setP2pActivityId(getP2pActivityId());
		p2pActivityImpl.setGroupId(getGroupId());
		p2pActivityImpl.setCompanyId(getCompanyId());
		p2pActivityImpl.setUserCreateId(getUserCreateId());
		p2pActivityImpl.setUserCreateName(getUserCreateName());
		p2pActivityImpl.setCreateDate(getCreateDate());
		p2pActivityImpl.setModifiedDate(getModifiedDate());
		p2pActivityImpl.setActId(getActId());
		p2pActivityImpl.setUserId(getUserId());
		p2pActivityImpl.setFileEntryId(getFileEntryId());
		p2pActivityImpl.setCountCorrections(getCountCorrections());
		p2pActivityImpl.setDescription(getDescription());
		p2pActivityImpl.setDate(getDate());
		p2pActivityImpl.setAsignationsCompleted(isAsignationsCompleted());

		p2pActivityImpl.resetOriginalValues();

		return p2pActivityImpl;
	}

	@Override
	public int compareTo(P2PActivity p2pActivity) {
		int value = 0;

		if (getCountCorrections() < p2pActivity.getCountCorrections()) {
			value = -1;
		}
		else if (getCountCorrections() > p2pActivity.getCountCorrections()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getP2pActivityId() < p2pActivity.getP2pActivityId()) {
			value = -1;
		}
		else if (getP2pActivityId() > p2pActivity.getP2pActivityId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof P2PActivity)) {
			return false;
		}

		P2PActivity p2pActivity = (P2PActivity)obj;

		long primaryKey = p2pActivity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		P2PActivityModelImpl p2pActivityModelImpl = this;

		p2pActivityModelImpl._originalUuid = p2pActivityModelImpl._uuid;

		p2pActivityModelImpl._originalGroupId = p2pActivityModelImpl._groupId;

		p2pActivityModelImpl._setOriginalGroupId = false;

		p2pActivityModelImpl._originalCompanyId = p2pActivityModelImpl._companyId;

		p2pActivityModelImpl._setOriginalCompanyId = false;

		p2pActivityModelImpl._setModifiedDate = false;

		p2pActivityModelImpl._originalActId = p2pActivityModelImpl._actId;

		p2pActivityModelImpl._setOriginalActId = false;

		p2pActivityModelImpl._originalUserId = p2pActivityModelImpl._userId;

		p2pActivityModelImpl._setOriginalUserId = false;

		p2pActivityModelImpl._originalAsignationsCompleted = p2pActivityModelImpl._asignationsCompleted;

		p2pActivityModelImpl._setOriginalAsignationsCompleted = false;

		p2pActivityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<P2PActivity> toCacheModel() {
		P2PActivityCacheModel p2pActivityCacheModel = new P2PActivityCacheModel();

		p2pActivityCacheModel.uuid = getUuid();

		String uuid = p2pActivityCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			p2pActivityCacheModel.uuid = null;
		}

		p2pActivityCacheModel.p2pActivityId = getP2pActivityId();

		p2pActivityCacheModel.groupId = getGroupId();

		p2pActivityCacheModel.companyId = getCompanyId();

		p2pActivityCacheModel.userCreateId = getUserCreateId();

		p2pActivityCacheModel.userCreateName = getUserCreateName();

		String userCreateName = p2pActivityCacheModel.userCreateName;

		if ((userCreateName != null) && (userCreateName.length() == 0)) {
			p2pActivityCacheModel.userCreateName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			p2pActivityCacheModel.createDate = createDate.getTime();
		}
		else {
			p2pActivityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			p2pActivityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			p2pActivityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		p2pActivityCacheModel.actId = getActId();

		p2pActivityCacheModel.userId = getUserId();

		p2pActivityCacheModel.fileEntryId = getFileEntryId();

		p2pActivityCacheModel.countCorrections = getCountCorrections();

		p2pActivityCacheModel.description = getDescription();

		String description = p2pActivityCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			p2pActivityCacheModel.description = null;
		}

		Date date = getDate();

		if (date != null) {
			p2pActivityCacheModel.date = date.getTime();
		}
		else {
			p2pActivityCacheModel.date = Long.MIN_VALUE;
		}

		p2pActivityCacheModel.asignationsCompleted = isAsignationsCompleted();

		return p2pActivityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", p2pActivityId=");
		sb.append(getP2pActivityId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userCreateId=");
		sb.append(getUserCreateId());
		sb.append(", userCreateName=");
		sb.append(getUserCreateName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", actId=");
		sb.append(getActId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", countCorrections=");
		sb.append(getCountCorrections());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", asignationsCompleted=");
		sb.append(isAsignationsCompleted());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.ted.lms.learning.activity.p2p.model.P2PActivity");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>p2pActivityId</column-name><column-value><![CDATA[");
		sb.append(getP2pActivityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreateId</column-name><column-value><![CDATA[");
		sb.append(getUserCreateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreateName</column-name><column-value><![CDATA[");
		sb.append(getUserCreateName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actId</column-name><column-value><![CDATA[");
		sb.append(getActId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countCorrections</column-name><column-value><![CDATA[");
		sb.append(getCountCorrections());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>asignationsCompleted</column-name><column-value><![CDATA[");
		sb.append(isAsignationsCompleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = P2PActivity.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			P2PActivity.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _p2pActivityId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userCreateId;
	private String _userCreateName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _actId;
	private long _originalActId;
	private boolean _setOriginalActId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _fileEntryId;
	private long _countCorrections;
	private String _description;
	private Date _date;
	private boolean _asignationsCompleted;
	private boolean _originalAsignationsCompleted;
	private boolean _setOriginalAsignationsCompleted;
	private long _columnBitmask;
	private P2PActivity _escapedModel;
}