/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.learning.activity.p2p.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.ted.lms.learning.activity.p2p.model.P2PActivityCorrections;
import com.ted.lms.learning.activity.p2p.model.P2PActivityCorrectionsModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the P2PActivityCorrections service. Represents a row in the &quot;LMS_P2PActivityCorrections&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link P2PActivityCorrectionsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link P2PActivityCorrectionsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see P2PActivityCorrectionsImpl
 * @see P2PActivityCorrections
 * @see P2PActivityCorrectionsModel
 * @generated
 */
@ProviderType
public class P2PActivityCorrectionsModelImpl extends BaseModelImpl<P2PActivityCorrections>
	implements P2PActivityCorrectionsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p2p activity corrections model instance should use the {@link P2PActivityCorrections} interface instead.
	 */
	public static final String TABLE_NAME = "LMS_P2PActivityCorrections";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "p2pActivityCorrectionsId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userCreateId", Types.BIGINT },
			{ "userCreateName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "p2pActivityId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "actId", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "date_", Types.TIMESTAMP },
			{ "fileEntryId", Types.BIGINT },
			{ "result", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("p2pActivityCorrectionsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userCreateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userCreateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("p2pActivityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("result", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table LMS_P2PActivityCorrections (uuid_ VARCHAR(75) null,p2pActivityCorrectionsId LONG not null primary key,groupId LONG,companyId LONG,userCreateId LONG,userCreateName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,p2pActivityId LONG,userId LONG,actId LONG,description VARCHAR(75) null,date_ DATE null,fileEntryId LONG,result LONG)";
	public static final String TABLE_SQL_DROP = "drop table LMS_P2PActivityCorrections";
	public static final String ORDER_BY_JPQL = " ORDER BY p2pActivityCorrections.p2pActivityCorrectionsId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LMS_P2PActivityCorrections.p2pActivityCorrectionsId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ted.lms.learning.activity.p2p.model.P2PActivityCorrections"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ted.lms.learning.activity.p2p.model.P2PActivityCorrections"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ted.lms.learning.activity.p2p.model.P2PActivityCorrections"),
			true);
	public static final long ACTID_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long P2PACTIVITYID_COLUMN_BITMASK = 8L;
	public static final long USERID_COLUMN_BITMASK = 16L;
	public static final long UUID_COLUMN_BITMASK = 32L;
	public static final long P2PACTIVITYCORRECTIONSID_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.ted.lms.learning.activity.p2p.service.util.ServiceProps.get(
				"lock.expiration.time.com.ted.lms.learning.activity.p2p.model.P2PActivityCorrections"));

	public P2PActivityCorrectionsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _p2pActivityCorrectionsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setP2pActivityCorrectionsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _p2pActivityCorrectionsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return P2PActivityCorrections.class;
	}

	@Override
	public String getModelClassName() {
		return P2PActivityCorrections.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("p2pActivityCorrectionsId", getP2pActivityCorrectionsId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userCreateId", getUserCreateId());
		attributes.put("userCreateName", getUserCreateName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("p2pActivityId", getP2pActivityId());
		attributes.put("userId", getUserId());
		attributes.put("actId", getActId());
		attributes.put("description", getDescription());
		attributes.put("date", getDate());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("result", getResult());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long p2pActivityCorrectionsId = (Long)attributes.get(
				"p2pActivityCorrectionsId");

		if (p2pActivityCorrectionsId != null) {
			setP2pActivityCorrectionsId(p2pActivityCorrectionsId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userCreateId = (Long)attributes.get("userCreateId");

		if (userCreateId != null) {
			setUserCreateId(userCreateId);
		}

		String userCreateName = (String)attributes.get("userCreateName");

		if (userCreateName != null) {
			setUserCreateName(userCreateName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long p2pActivityId = (Long)attributes.get("p2pActivityId");

		if (p2pActivityId != null) {
			setP2pActivityId(p2pActivityId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long actId = (Long)attributes.get("actId");

		if (actId != null) {
			setActId(actId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Long result = (Long)attributes.get("result");

		if (result != null) {
			setResult(result);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getP2pActivityCorrectionsId() {
		return _p2pActivityCorrectionsId;
	}

	@Override
	public void setP2pActivityCorrectionsId(long p2pActivityCorrectionsId) {
		_p2pActivityCorrectionsId = p2pActivityCorrectionsId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserCreateId() {
		return _userCreateId;
	}

	@Override
	public void setUserCreateId(long userCreateId) {
		_userCreateId = userCreateId;
	}

	@Override
	public String getUserCreateName() {
		if (_userCreateName == null) {
			return "";
		}
		else {
			return _userCreateName;
		}
	}

	@Override
	public void setUserCreateName(String userCreateName) {
		_userCreateName = userCreateName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getP2pActivityId() {
		return _p2pActivityId;
	}

	@Override
	public void setP2pActivityId(long p2pActivityId) {
		_columnBitmask |= P2PACTIVITYID_COLUMN_BITMASK;

		if (!_setOriginalP2pActivityId) {
			_setOriginalP2pActivityId = true;

			_originalP2pActivityId = _p2pActivityId;
		}

		_p2pActivityId = p2pActivityId;
	}

	public long getOriginalP2pActivityId() {
		return _originalP2pActivityId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public long getActId() {
		return _actId;
	}

	@Override
	public void setActId(long actId) {
		_columnBitmask |= ACTID_COLUMN_BITMASK;

		if (!_setOriginalActId) {
			_setOriginalActId = true;

			_originalActId = _actId;
		}

		_actId = actId;
	}

	public long getOriginalActId() {
		return _originalActId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_date = date;
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	@Override
	public long getResult() {
		return _result;
	}

	@Override
	public void setResult(long result) {
		_result = result;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				P2PActivityCorrections.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			P2PActivityCorrections.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public P2PActivityCorrections toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (P2PActivityCorrections)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		P2PActivityCorrectionsImpl p2pActivityCorrectionsImpl = new P2PActivityCorrectionsImpl();

		p2pActivityCorrectionsImpl.setUuid(getUuid());
		p2pActivityCorrectionsImpl.setP2pActivityCorrectionsId(getP2pActivityCorrectionsId());
		p2pActivityCorrectionsImpl.setGroupId(getGroupId());
		p2pActivityCorrectionsImpl.setCompanyId(getCompanyId());
		p2pActivityCorrectionsImpl.setUserCreateId(getUserCreateId());
		p2pActivityCorrectionsImpl.setUserCreateName(getUserCreateName());
		p2pActivityCorrectionsImpl.setCreateDate(getCreateDate());
		p2pActivityCorrectionsImpl.setModifiedDate(getModifiedDate());
		p2pActivityCorrectionsImpl.setP2pActivityId(getP2pActivityId());
		p2pActivityCorrectionsImpl.setUserId(getUserId());
		p2pActivityCorrectionsImpl.setActId(getActId());
		p2pActivityCorrectionsImpl.setDescription(getDescription());
		p2pActivityCorrectionsImpl.setDate(getDate());
		p2pActivityCorrectionsImpl.setFileEntryId(getFileEntryId());
		p2pActivityCorrectionsImpl.setResult(getResult());

		p2pActivityCorrectionsImpl.resetOriginalValues();

		return p2pActivityCorrectionsImpl;
	}

	@Override
	public int compareTo(P2PActivityCorrections p2pActivityCorrections) {
		long primaryKey = p2pActivityCorrections.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof P2PActivityCorrections)) {
			return false;
		}

		P2PActivityCorrections p2pActivityCorrections = (P2PActivityCorrections)obj;

		long primaryKey = p2pActivityCorrections.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		P2PActivityCorrectionsModelImpl p2pActivityCorrectionsModelImpl = this;

		p2pActivityCorrectionsModelImpl._originalUuid = p2pActivityCorrectionsModelImpl._uuid;

		p2pActivityCorrectionsModelImpl._originalGroupId = p2pActivityCorrectionsModelImpl._groupId;

		p2pActivityCorrectionsModelImpl._setOriginalGroupId = false;

		p2pActivityCorrectionsModelImpl._originalCompanyId = p2pActivityCorrectionsModelImpl._companyId;

		p2pActivityCorrectionsModelImpl._setOriginalCompanyId = false;

		p2pActivityCorrectionsModelImpl._setModifiedDate = false;

		p2pActivityCorrectionsModelImpl._originalP2pActivityId = p2pActivityCorrectionsModelImpl._p2pActivityId;

		p2pActivityCorrectionsModelImpl._setOriginalP2pActivityId = false;

		p2pActivityCorrectionsModelImpl._originalUserId = p2pActivityCorrectionsModelImpl._userId;

		p2pActivityCorrectionsModelImpl._setOriginalUserId = false;

		p2pActivityCorrectionsModelImpl._originalActId = p2pActivityCorrectionsModelImpl._actId;

		p2pActivityCorrectionsModelImpl._setOriginalActId = false;

		p2pActivityCorrectionsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<P2PActivityCorrections> toCacheModel() {
		P2PActivityCorrectionsCacheModel p2pActivityCorrectionsCacheModel = new P2PActivityCorrectionsCacheModel();

		p2pActivityCorrectionsCacheModel.uuid = getUuid();

		String uuid = p2pActivityCorrectionsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			p2pActivityCorrectionsCacheModel.uuid = null;
		}

		p2pActivityCorrectionsCacheModel.p2pActivityCorrectionsId = getP2pActivityCorrectionsId();

		p2pActivityCorrectionsCacheModel.groupId = getGroupId();

		p2pActivityCorrectionsCacheModel.companyId = getCompanyId();

		p2pActivityCorrectionsCacheModel.userCreateId = getUserCreateId();

		p2pActivityCorrectionsCacheModel.userCreateName = getUserCreateName();

		String userCreateName = p2pActivityCorrectionsCacheModel.userCreateName;

		if ((userCreateName != null) && (userCreateName.length() == 0)) {
			p2pActivityCorrectionsCacheModel.userCreateName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			p2pActivityCorrectionsCacheModel.createDate = createDate.getTime();
		}
		else {
			p2pActivityCorrectionsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			p2pActivityCorrectionsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			p2pActivityCorrectionsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		p2pActivityCorrectionsCacheModel.p2pActivityId = getP2pActivityId();

		p2pActivityCorrectionsCacheModel.userId = getUserId();

		p2pActivityCorrectionsCacheModel.actId = getActId();

		p2pActivityCorrectionsCacheModel.description = getDescription();

		String description = p2pActivityCorrectionsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			p2pActivityCorrectionsCacheModel.description = null;
		}

		Date date = getDate();

		if (date != null) {
			p2pActivityCorrectionsCacheModel.date = date.getTime();
		}
		else {
			p2pActivityCorrectionsCacheModel.date = Long.MIN_VALUE;
		}

		p2pActivityCorrectionsCacheModel.fileEntryId = getFileEntryId();

		p2pActivityCorrectionsCacheModel.result = getResult();

		return p2pActivityCorrectionsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", p2pActivityCorrectionsId=");
		sb.append(getP2pActivityCorrectionsId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userCreateId=");
		sb.append(getUserCreateId());
		sb.append(", userCreateName=");
		sb.append(getUserCreateName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", p2pActivityId=");
		sb.append(getP2pActivityId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", actId=");
		sb.append(getActId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", result=");
		sb.append(getResult());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append(
			"com.ted.lms.learning.activity.p2p.model.P2PActivityCorrections");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>p2pActivityCorrectionsId</column-name><column-value><![CDATA[");
		sb.append(getP2pActivityCorrectionsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreateId</column-name><column-value><![CDATA[");
		sb.append(getUserCreateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreateName</column-name><column-value><![CDATA[");
		sb.append(getUserCreateName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>p2pActivityId</column-name><column-value><![CDATA[");
		sb.append(getP2pActivityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actId</column-name><column-value><![CDATA[");
		sb.append(getActId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>result</column-name><column-value><![CDATA[");
		sb.append(getResult());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = P2PActivityCorrections.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			P2PActivityCorrections.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _p2pActivityCorrectionsId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userCreateId;
	private String _userCreateName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _p2pActivityId;
	private long _originalP2pActivityId;
	private boolean _setOriginalP2pActivityId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _actId;
	private long _originalActId;
	private boolean _setOriginalActId;
	private String _description;
	private Date _date;
	private long _fileEntryId;
	private long _result;
	private long _columnBitmask;
	private P2PActivityCorrections _escapedModel;
}