/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.prerequisite.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PrerequisiteRelation service. Represents a row in the &quot;pre_PrerequisiteRelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.prerequisite.model.impl.PrerequisiteRelationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.prerequisite.model.impl.PrerequisiteRelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PrerequisiteRelation
 * @see com.ted.prerequisite.model.impl.PrerequisiteRelationImpl
 * @see com.ted.prerequisite.model.impl.PrerequisiteRelationModelImpl
 * @generated
 */
@ProviderType
public interface PrerequisiteRelationModel extends AttachedModel,
	BaseModel<PrerequisiteRelation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prerequisite relation model instance should use the {@link PrerequisiteRelation} interface instead.
	 */

	/**
	 * Returns the primary key of this prerequisite relation.
	 *
	 * @return the primary key of this prerequisite relation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this prerequisite relation.
	 *
	 * @param primaryKey the primary key of this prerequisite relation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this prerequisite relation.
	 *
	 * @return the uuid of this prerequisite relation
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this prerequisite relation.
	 *
	 * @param uuid the uuid of this prerequisite relation
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the prerequisite relation ID of this prerequisite relation.
	 *
	 * @return the prerequisite relation ID of this prerequisite relation
	 */
	public long getPrerequisiteRelationId();

	/**
	 * Sets the prerequisite relation ID of this prerequisite relation.
	 *
	 * @param prerequisiteRelationId the prerequisite relation ID of this prerequisite relation
	 */
	public void setPrerequisiteRelationId(long prerequisiteRelationId);

	/**
	 * Returns the class name prerequisite ID of this prerequisite relation.
	 *
	 * @return the class name prerequisite ID of this prerequisite relation
	 */
	public long getClassNamePrerequisiteId();

	/**
	 * Sets the class name prerequisite ID of this prerequisite relation.
	 *
	 * @param classNamePrerequisiteId the class name prerequisite ID of this prerequisite relation
	 */
	public void setClassNamePrerequisiteId(long classNamePrerequisiteId);

	/**
	 * Returns the fully qualified class name of this prerequisite relation.
	 *
	 * @return the fully qualified class name of this prerequisite relation
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this prerequisite relation.
	 *
	 * @return the class name ID of this prerequisite relation
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this prerequisite relation.
	 *
	 * @param classNameId the class name ID of this prerequisite relation
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this prerequisite relation.
	 *
	 * @return the class pk of this prerequisite relation
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this prerequisite relation.
	 *
	 * @param classPK the class pk of this prerequisite relation
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the extra data of this prerequisite relation.
	 *
	 * @return the extra data of this prerequisite relation
	 */
	@AutoEscape
	public String getExtraData();

	/**
	 * Sets the extra data of this prerequisite relation.
	 *
	 * @param extraData the extra data of this prerequisite relation
	 */
	public void setExtraData(String extraData);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PrerequisiteRelation prerequisiteRelation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PrerequisiteRelation> toCacheModel();

	@Override
	public PrerequisiteRelation toEscapedModel();

	@Override
	public PrerequisiteRelation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}