/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.inscription.teams.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Schedule service. Represents a row in the &quot;iteam_Schedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.lms.inscription.teams.model.impl.ScheduleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.lms.inscription.teams.model.impl.ScheduleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Schedule
 * @see com.ted.lms.inscription.teams.model.impl.ScheduleImpl
 * @see com.ted.lms.inscription.teams.model.impl.ScheduleModelImpl
 * @generated
 */
@ProviderType
public interface ScheduleModel extends BaseModel<Schedule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a schedule model instance should use the {@link Schedule} interface instead.
	 */

	/**
	 * Returns the primary key of this schedule.
	 *
	 * @return the primary key of this schedule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this schedule.
	 *
	 * @param primaryKey the primary key of this schedule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the schedule ID of this schedule.
	 *
	 * @return the schedule ID of this schedule
	 */
	public long getScheduleId();

	/**
	 * Sets the schedule ID of this schedule.
	 *
	 * @param scheduleId the schedule ID of this schedule
	 */
	public void setScheduleId(long scheduleId);

	/**
	 * Returns the team ID of this schedule.
	 *
	 * @return the team ID of this schedule
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this schedule.
	 *
	 * @param teamId the team ID of this schedule
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the start date of this schedule.
	 *
	 * @return the start date of this schedule
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this schedule.
	 *
	 * @param startDate the start date of this schedule
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this schedule.
	 *
	 * @return the end date of this schedule
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this schedule.
	 *
	 * @param endDate the end date of this schedule
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Schedule schedule);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Schedule> toCacheModel();

	@Override
	public Schedule toEscapedModel();

	@Override
	public Schedule toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}