create table LMS_Course (
	uuid_ VARCHAR(75) null,
	courseId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	parentCourseId LONG,
	groupCreatedId LONG,
	title STRING null,
	description STRING null,
	smallImageId LONG,
	registrationStartDate DATE null,
	registrationEndDate DATE null,
	executionStartDate DATE null,
	executionEndDate DATE null,
	maxUsers INTEGER,
	inscriptionType LONG,
	courseEvalId LONG,
	calificationType LONG,
	welcome BOOLEAN,
	welcomeSubject VARCHAR(75) null,
	welcomeMsg TEXT null,
	goodbye BOOLEAN,
	goodbyeSubject VARCHAR(75) null,
	goodbyeMsg TEXT null,
	courseExtraData TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table LMS_CourseResult (
	crId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userModifiedId LONG,
	userModifiedName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	courseId LONG,
	userId LONG,
	result DOUBLE,
	comments TEXT null,
	passed BOOLEAN,
	registrationDate DATE null,
	startDate DATE null,
	passedDate DATE null,
	allowStartDate DATE null,
	allowEndDate DATE null,
	extraData TEXT null
);

create table LMS_LearningActivity (
	uuid_ VARCHAR(75) null,
	actId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	moduleId LONG,
	title STRING null,
	description STRING null,
	typeId LONG,
	startDate DATE null,
	endDate DATE null,
	tries INTEGER,
	passPuntuation INTEGER,
	priority LONG,
	extraContent TEXT null,
	feedbackCorrect VARCHAR(75) null,
	feedbackNoCorrect VARCHAR(75) null,
	required BOOLEAN,
	commentsActivated BOOLEAN,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table LMS_LearningActivityResult (
	uuid_ VARCHAR(75) null,
	larId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userModifiedId LONG,
	userModifiedName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	actId LONG,
	userId LONG,
	result DOUBLE,
	comments TEXT null,
	passed BOOLEAN,
	startDate DATE null,
	endDate DATE null,
	extraData TEXT null
);

create table LMS_LearningActivityTry (
	uuid_ VARCHAR(75) null,
	latId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userModifiedId LONG,
	userModifiedName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	actId LONG,
	userId LONG,
	result DOUBLE,
	comments TEXT null,
	startDate DATE null,
	endDate DATE null,
	endUserDate DATE null,
	tryResultData TEXT null
);

create table LMS_Module (
	uuid_ VARCHAR(75) null,
	moduleId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	title STRING null,
	description STRING null,
	smallImageId LONG,
	order_ LONG,
	startDate DATE null,
	endDate DATE null,
	allowedTime LONG,
	moduleEvalId LONG,
	moduleExtraData TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table LMS_ModuleResult (
	mrId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userModifiedId LONG,
	userModifiedName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	moduleId LONG,
	userId LONG,
	result DOUBLE,
	comments TEXT null,
	passed BOOLEAN,
	startDate DATE null,
	passedDate DATE null,
	extraData TEXT null
);