/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import com.ted.lms.service.persistence.CourseTypeRelationPK;

import java.io.Serializable;

/**
 * The base model interface for the CourseTypeRelation service. Represents a row in the &quot;LMS_CourseTypeRelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.lms.model.impl.CourseTypeRelationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.lms.model.impl.CourseTypeRelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseTypeRelation
 * @see com.ted.lms.model.impl.CourseTypeRelationImpl
 * @see com.ted.lms.model.impl.CourseTypeRelationModelImpl
 * @generated
 */
@ProviderType
public interface CourseTypeRelationModel extends AttachedModel,
	BaseModel<CourseTypeRelation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course type relation model instance should use the {@link CourseTypeRelation} interface instead.
	 */

	/**
	 * Returns the primary key of this course type relation.
	 *
	 * @return the primary key of this course type relation
	 */
	public CourseTypeRelationPK getPrimaryKey();

	/**
	 * Sets the primary key of this course type relation.
	 *
	 * @param primaryKey the primary key of this course type relation
	 */
	public void setPrimaryKey(CourseTypeRelationPK primaryKey);

	/**
	 * Returns the course type ID of this course type relation.
	 *
	 * @return the course type ID of this course type relation
	 */
	public long getCourseTypeId();

	/**
	 * Sets the course type ID of this course type relation.
	 *
	 * @param courseTypeId the course type ID of this course type relation
	 */
	public void setCourseTypeId(long courseTypeId);

	/**
	 * Returns the fully qualified class name of this course type relation.
	 *
	 * @return the fully qualified class name of this course type relation
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this course type relation.
	 *
	 * @return the class name ID of this course type relation
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this course type relation.
	 *
	 * @param classNameId the class name ID of this course type relation
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this course type relation.
	 *
	 * @return the class pk of this course type relation
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this course type relation.
	 *
	 * @param classPK the class pk of this course type relation
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CourseTypeRelation courseTypeRelation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CourseTypeRelation> toCacheModel();

	@Override
	public CourseTypeRelation toEscapedModel();

	@Override
	public CourseTypeRelation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}