/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Course service. Represents a row in the &quot;LMS_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.lms.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.lms.model.impl.CourseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Course
 * @see com.ted.lms.model.impl.CourseImpl
 * @see com.ted.lms.model.impl.CourseModelImpl
 * @generated
 */
@ProviderType
public interface CourseModel extends BaseModel<Course>, LocalizedModel,
	ShardedModel, StagedGroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this course.
	 *
	 * @return the uuid of this course
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this course.
	 *
	 * @param uuid the uuid of this course
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the course ID of this course.
	 *
	 * @return the course ID of this course
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course.
	 *
	 * @param courseId the course ID of this course
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the group ID of this course.
	 *
	 * @return the group ID of this course
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this course.
	 *
	 * @param groupId the group ID of this course
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this course.
	 *
	 * @return the company ID of this course
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this course.
	 *
	 * @param companyId the company ID of this course
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this course.
	 *
	 * @return the user ID of this course
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this course.
	 *
	 * @param userId the user ID of this course
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course.
	 *
	 * @return the user uuid of this course
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this course.
	 *
	 * @param userUuid the user uuid of this course
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this course.
	 *
	 * @return the user name of this course
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this course.
	 *
	 * @param userName the user name of this course
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this course.
	 *
	 * @return the create date of this course
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this course.
	 *
	 * @param createDate the create date of this course
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course.
	 *
	 * @return the modified date of this course
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course.
	 *
	 * @param modifiedDate the modified date of this course
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the last publish date of this course.
	 *
	 * @return the last publish date of this course
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this course.
	 *
	 * @param lastPublishDate the last publish date of this course
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the parent course ID of this course.
	 *
	 * @return the parent course ID of this course
	 */
	public long getParentCourseId();

	/**
	 * Sets the parent course ID of this course.
	 *
	 * @param parentCourseId the parent course ID of this course
	 */
	public void setParentCourseId(long parentCourseId);

	/**
	 * Returns the group created ID of this course.
	 *
	 * @return the group created ID of this course
	 */
	public long getGroupCreatedId();

	/**
	 * Sets the group created ID of this course.
	 *
	 * @param groupCreatedId the group created ID of this course
	 */
	public void setGroupCreatedId(long groupCreatedId);

	/**
	 * Returns the title of this course.
	 *
	 * @return the title of this course
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this course
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this course. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this course
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this course
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this course.
	 *
	 * @return the locales and localized titles of this course
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this course.
	 *
	 * @param title the title of this course
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this course in the language.
	 *
	 * @param title the localized title of this course
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this course in the language, and sets the default locale.
	 *
	 * @param title the localized title of this course
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this course from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this course
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this course from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this course
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this course.
	 *
	 * @return the description of this course
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this course
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this course. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this course
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this course
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this course.
	 *
	 * @return the locales and localized descriptions of this course
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this course.
	 *
	 * @param description the description of this course
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this course in the language.
	 *
	 * @param description the localized description of this course
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this course in the language, and sets the default locale.
	 *
	 * @param description the localized description of this course
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this course from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this course
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this course from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this course
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the small image ID of this course.
	 *
	 * @return the small image ID of this course
	 */
	public long getSmallImageId();

	/**
	 * Sets the small image ID of this course.
	 *
	 * @param smallImageId the small image ID of this course
	 */
	public void setSmallImageId(long smallImageId);

	/**
	 * Returns the registration start date of this course.
	 *
	 * @return the registration start date of this course
	 */
	public Date getRegistrationStartDate();

	/**
	 * Sets the registration start date of this course.
	 *
	 * @param registrationStartDate the registration start date of this course
	 */
	public void setRegistrationStartDate(Date registrationStartDate);

	/**
	 * Returns the registration end date of this course.
	 *
	 * @return the registration end date of this course
	 */
	public Date getRegistrationEndDate();

	/**
	 * Sets the registration end date of this course.
	 *
	 * @param registrationEndDate the registration end date of this course
	 */
	public void setRegistrationEndDate(Date registrationEndDate);

	/**
	 * Returns the execution start date of this course.
	 *
	 * @return the execution start date of this course
	 */
	public Date getExecutionStartDate();

	/**
	 * Sets the execution start date of this course.
	 *
	 * @param executionStartDate the execution start date of this course
	 */
	public void setExecutionStartDate(Date executionStartDate);

	/**
	 * Returns the execution end date of this course.
	 *
	 * @return the execution end date of this course
	 */
	public Date getExecutionEndDate();

	/**
	 * Sets the execution end date of this course.
	 *
	 * @param executionEndDate the execution end date of this course
	 */
	public void setExecutionEndDate(Date executionEndDate);

	/**
	 * Returns the max users of this course.
	 *
	 * @return the max users of this course
	 */
	public int getMaxUsers();

	/**
	 * Sets the max users of this course.
	 *
	 * @param maxUsers the max users of this course
	 */
	public void setMaxUsers(int maxUsers);

	/**
	 * Returns the inscription type of this course.
	 *
	 * @return the inscription type of this course
	 */
	public long getInscriptionType();

	/**
	 * Sets the inscription type of this course.
	 *
	 * @param inscriptionType the inscription type of this course
	 */
	public void setInscriptionType(long inscriptionType);

	/**
	 * Returns the course eval ID of this course.
	 *
	 * @return the course eval ID of this course
	 */
	public long getCourseEvalId();

	/**
	 * Sets the course eval ID of this course.
	 *
	 * @param courseEvalId the course eval ID of this course
	 */
	public void setCourseEvalId(long courseEvalId);

	/**
	 * Returns the calification type of this course.
	 *
	 * @return the calification type of this course
	 */
	public long getCalificationType();

	/**
	 * Sets the calification type of this course.
	 *
	 * @param calificationType the calification type of this course
	 */
	public void setCalificationType(long calificationType);

	/**
	 * Returns the welcome of this course.
	 *
	 * @return the welcome of this course
	 */
	public boolean getWelcome();

	/**
	 * Returns <code>true</code> if this course is welcome.
	 *
	 * @return <code>true</code> if this course is welcome; <code>false</code> otherwise
	 */
	public boolean isWelcome();

	/**
	 * Sets whether this course is welcome.
	 *
	 * @param welcome the welcome of this course
	 */
	public void setWelcome(boolean welcome);

	/**
	 * Returns the welcome subject of this course.
	 *
	 * @return the welcome subject of this course
	 */
	@AutoEscape
	public String getWelcomeSubject();

	/**
	 * Sets the welcome subject of this course.
	 *
	 * @param welcomeSubject the welcome subject of this course
	 */
	public void setWelcomeSubject(String welcomeSubject);

	/**
	 * Returns the welcome msg of this course.
	 *
	 * @return the welcome msg of this course
	 */
	@AutoEscape
	public String getWelcomeMsg();

	/**
	 * Sets the welcome msg of this course.
	 *
	 * @param welcomeMsg the welcome msg of this course
	 */
	public void setWelcomeMsg(String welcomeMsg);

	/**
	 * Returns the goodbye of this course.
	 *
	 * @return the goodbye of this course
	 */
	public boolean getGoodbye();

	/**
	 * Returns <code>true</code> if this course is goodbye.
	 *
	 * @return <code>true</code> if this course is goodbye; <code>false</code> otherwise
	 */
	public boolean isGoodbye();

	/**
	 * Sets whether this course is goodbye.
	 *
	 * @param goodbye the goodbye of this course
	 */
	public void setGoodbye(boolean goodbye);

	/**
	 * Returns the goodbye subject of this course.
	 *
	 * @return the goodbye subject of this course
	 */
	@AutoEscape
	public String getGoodbyeSubject();

	/**
	 * Sets the goodbye subject of this course.
	 *
	 * @param goodbyeSubject the goodbye subject of this course
	 */
	public void setGoodbyeSubject(String goodbyeSubject);

	/**
	 * Returns the goodbye msg of this course.
	 *
	 * @return the goodbye msg of this course
	 */
	@AutoEscape
	public String getGoodbyeMsg();

	/**
	 * Sets the goodbye msg of this course.
	 *
	 * @param goodbyeMsg the goodbye msg of this course
	 */
	public void setGoodbyeMsg(String goodbyeMsg);

	/**
	 * Returns the course extra data of this course.
	 *
	 * @return the course extra data of this course
	 */
	@AutoEscape
	public String getCourseExtraData();

	/**
	 * Sets the course extra data of this course.
	 *
	 * @param courseExtraData the course extra data of this course
	 */
	public void setCourseExtraData(String courseExtraData);

	/**
	 * Returns the status of this course.
	 *
	 * @return the status of this course
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this course.
	 *
	 * @param status the status of this course
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this course.
	 *
	 * @return the status by user ID of this course
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this course.
	 *
	 * @param statusByUserId the status by user ID of this course
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this course.
	 *
	 * @return the status by user uuid of this course
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this course.
	 *
	 * @param statusByUserUuid the status by user uuid of this course
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this course.
	 *
	 * @return the status by user name of this course
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this course.
	 *
	 * @param statusByUserName the status by user name of this course
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this course.
	 *
	 * @return the status date of this course
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this course.
	 *
	 * @param statusDate the status date of this course
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this course is approved.
	 *
	 * @return <code>true</code> if this course is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this course is denied.
	 *
	 * @return <code>true</code> if this course is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this course is a draft.
	 *
	 * @return <code>true</code> if this course is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this course is expired.
	 *
	 * @return <code>true</code> if this course is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this course is inactive.
	 *
	 * @return <code>true</code> if this course is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this course is incomplete.
	 *
	 * @return <code>true</code> if this course is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this course is pending.
	 *
	 * @return <code>true</code> if this course is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this course is scheduled.
	 *
	 * @return <code>true</code> if this course is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(Course course);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Course> toCacheModel();

	@Override
	public Course toEscapedModel();

	@Override
	public Course toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}