/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LearningActivityTry service. Represents a row in the &quot;LMS_LearningActivityTry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ted.lms.model.impl.LearningActivityTryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ted.lms.model.impl.LearningActivityTryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LearningActivityTry
 * @generated
 */
@ProviderType
public interface LearningActivityTryModel
	extends BaseModel<LearningActivityTry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a learning activity try model instance should use the {@link LearningActivityTry} interface instead.
	 */

	/**
	 * Returns the primary key of this learning activity try.
	 *
	 * @return the primary key of this learning activity try
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this learning activity try.
	 *
	 * @param primaryKey the primary key of this learning activity try
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this learning activity try.
	 *
	 * @return the uuid of this learning activity try
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this learning activity try.
	 *
	 * @param uuid the uuid of this learning activity try
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lat ID of this learning activity try.
	 *
	 * @return the lat ID of this learning activity try
	 */
	public long getLatId();

	/**
	 * Sets the lat ID of this learning activity try.
	 *
	 * @param latId the lat ID of this learning activity try
	 */
	public void setLatId(long latId);

	/**
	 * Returns the group ID of this learning activity try.
	 *
	 * @return the group ID of this learning activity try
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this learning activity try.
	 *
	 * @param groupId the group ID of this learning activity try
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this learning activity try.
	 *
	 * @return the company ID of this learning activity try
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this learning activity try.
	 *
	 * @param companyId the company ID of this learning activity try
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user modified ID of this learning activity try.
	 *
	 * @return the user modified ID of this learning activity try
	 */
	public long getUserModifiedId();

	/**
	 * Sets the user modified ID of this learning activity try.
	 *
	 * @param userModifiedId the user modified ID of this learning activity try
	 */
	public void setUserModifiedId(long userModifiedId);

	/**
	 * Returns the user modified name of this learning activity try.
	 *
	 * @return the user modified name of this learning activity try
	 */
	@AutoEscape
	public String getUserModifiedName();

	/**
	 * Sets the user modified name of this learning activity try.
	 *
	 * @param userModifiedName the user modified name of this learning activity try
	 */
	public void setUserModifiedName(String userModifiedName);

	/**
	 * Returns the create date of this learning activity try.
	 *
	 * @return the create date of this learning activity try
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this learning activity try.
	 *
	 * @param createDate the create date of this learning activity try
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this learning activity try.
	 *
	 * @return the modified date of this learning activity try
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this learning activity try.
	 *
	 * @param modifiedDate the modified date of this learning activity try
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the act ID of this learning activity try.
	 *
	 * @return the act ID of this learning activity try
	 */
	public long getActId();

	/**
	 * Sets the act ID of this learning activity try.
	 *
	 * @param actId the act ID of this learning activity try
	 */
	public void setActId(long actId);

	/**
	 * Returns the user ID of this learning activity try.
	 *
	 * @return the user ID of this learning activity try
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this learning activity try.
	 *
	 * @param userId the user ID of this learning activity try
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this learning activity try.
	 *
	 * @return the user uuid of this learning activity try
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this learning activity try.
	 *
	 * @param userUuid the user uuid of this learning activity try
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the result of this learning activity try.
	 *
	 * @return the result of this learning activity try
	 */
	public double getResult();

	/**
	 * Sets the result of this learning activity try.
	 *
	 * @param result the result of this learning activity try
	 */
	public void setResult(double result);

	/**
	 * Returns the comments of this learning activity try.
	 *
	 * @return the comments of this learning activity try
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this learning activity try.
	 *
	 * @param comments the comments of this learning activity try
	 */
	public void setComments(String comments);

	/**
	 * Returns the start date of this learning activity try.
	 *
	 * @return the start date of this learning activity try
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this learning activity try.
	 *
	 * @param startDate the start date of this learning activity try
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this learning activity try.
	 *
	 * @return the end date of this learning activity try
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this learning activity try.
	 *
	 * @param endDate the end date of this learning activity try
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the end user date of this learning activity try.
	 *
	 * @return the end user date of this learning activity try
	 */
	public Date getEndUserDate();

	/**
	 * Sets the end user date of this learning activity try.
	 *
	 * @param endUserDate the end user date of this learning activity try
	 */
	public void setEndUserDate(Date endUserDate);

	/**
	 * Returns the try result data of this learning activity try.
	 *
	 * @return the try result data of this learning activity try
	 */
	@AutoEscape
	public String getTryResultData();

	/**
	 * Sets the try result data of this learning activity try.
	 *
	 * @param tryResultData the try result data of this learning activity try
	 */
	public void setTryResultData(String tryResultData);

}