/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Module service. Represents a row in the &quot;LMS_Module&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.lms.model.impl.ModuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.lms.model.impl.ModuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Module
 * @see com.ted.lms.model.impl.ModuleImpl
 * @see com.ted.lms.model.impl.ModuleModelImpl
 * @generated
 */
@ProviderType
public interface ModuleModel extends BaseModel<Module>, GroupedModel,
	LocalizedModel, ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a module model instance should use the {@link Module} interface instead.
	 */

	/**
	 * Returns the primary key of this module.
	 *
	 * @return the primary key of this module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this module.
	 *
	 * @param primaryKey the primary key of this module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this module.
	 *
	 * @return the uuid of this module
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this module.
	 *
	 * @param uuid the uuid of this module
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the module ID of this module.
	 *
	 * @return the module ID of this module
	 */
	public long getModuleId();

	/**
	 * Sets the module ID of this module.
	 *
	 * @param moduleId the module ID of this module
	 */
	public void setModuleId(long moduleId);

	/**
	 * Returns the group ID of this module.
	 *
	 * @return the group ID of this module
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this module.
	 *
	 * @param groupId the group ID of this module
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this module.
	 *
	 * @return the company ID of this module
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this module.
	 *
	 * @param companyId the company ID of this module
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this module.
	 *
	 * @return the user ID of this module
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this module.
	 *
	 * @param userId the user ID of this module
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this module.
	 *
	 * @return the user uuid of this module
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this module.
	 *
	 * @param userUuid the user uuid of this module
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this module.
	 *
	 * @return the user name of this module
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this module.
	 *
	 * @param userName the user name of this module
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this module.
	 *
	 * @return the create date of this module
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this module.
	 *
	 * @param createDate the create date of this module
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this module.
	 *
	 * @return the modified date of this module
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this module.
	 *
	 * @param modifiedDate the modified date of this module
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this module.
	 *
	 * @return the title of this module
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this module in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this module
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this module in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this module. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this module in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this module
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this module in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this module
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this module.
	 *
	 * @return the locales and localized titles of this module
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this module.
	 *
	 * @param title the title of this module
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this module in the language.
	 *
	 * @param title the localized title of this module
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this module in the language, and sets the default locale.
	 *
	 * @param title the localized title of this module
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this module from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this module
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this module from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this module
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this module.
	 *
	 * @return the description of this module
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this module in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this module
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this module in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this module. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this module in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this module
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this module in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this module
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this module.
	 *
	 * @return the locales and localized descriptions of this module
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this module.
	 *
	 * @param description the description of this module
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this module in the language.
	 *
	 * @param description the localized description of this module
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this module in the language, and sets the default locale.
	 *
	 * @param description the localized description of this module
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this module from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this module
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this module from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this module
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the small image ID of this module.
	 *
	 * @return the small image ID of this module
	 */
	public long getSmallImageId();

	/**
	 * Sets the small image ID of this module.
	 *
	 * @param smallImageId the small image ID of this module
	 */
	public void setSmallImageId(long smallImageId);

	/**
	 * Returns the order of this module.
	 *
	 * @return the order of this module
	 */
	public long getOrder();

	/**
	 * Sets the order of this module.
	 *
	 * @param order the order of this module
	 */
	public void setOrder(long order);

	/**
	 * Returns the start date of this module.
	 *
	 * @return the start date of this module
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this module.
	 *
	 * @param startDate the start date of this module
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this module.
	 *
	 * @return the end date of this module
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this module.
	 *
	 * @param endDate the end date of this module
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the allowed time of this module.
	 *
	 * @return the allowed time of this module
	 */
	public long getAllowedTime();

	/**
	 * Sets the allowed time of this module.
	 *
	 * @param allowedTime the allowed time of this module
	 */
	public void setAllowedTime(long allowedTime);

	/**
	 * Returns the module extra data of this module.
	 *
	 * @return the module extra data of this module
	 */
	@AutoEscape
	public String getModuleExtraData();

	/**
	 * Sets the module extra data of this module.
	 *
	 * @param moduleExtraData the module extra data of this module
	 */
	public void setModuleExtraData(String moduleExtraData);

	/**
	 * Returns the status of this module.
	 *
	 * @return the status of this module
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this module.
	 *
	 * @param status the status of this module
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this module.
	 *
	 * @return the status by user ID of this module
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this module.
	 *
	 * @param statusByUserId the status by user ID of this module
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this module.
	 *
	 * @return the status by user uuid of this module
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this module.
	 *
	 * @param statusByUserUuid the status by user uuid of this module
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this module.
	 *
	 * @return the status by user name of this module
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this module.
	 *
	 * @param statusByUserName the status by user name of this module
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this module.
	 *
	 * @return the status date of this module
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this module.
	 *
	 * @param statusDate the status date of this module
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this module is approved.
	 *
	 * @return <code>true</code> if this module is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this module is denied.
	 *
	 * @return <code>true</code> if this module is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this module is a draft.
	 *
	 * @return <code>true</code> if this module is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this module is expired.
	 *
	 * @return <code>true</code> if this module is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this module is inactive.
	 *
	 * @return <code>true</code> if this module is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this module is incomplete.
	 *
	 * @return <code>true</code> if this module is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this module is pending.
	 *
	 * @return <code>true</code> if this module is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this module is scheduled.
	 *
	 * @return <code>true</code> if this module is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(Module module);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Module> toCacheModel();

	@Override
	public Module toEscapedModel();

	@Override
	public Module toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}