/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.audit.db.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditEntry service. Represents a row in the &quot;audit_AuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.audit.db.model.impl.AuditEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.audit.db.model.impl.AuditEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntry
 * @see com.ted.audit.db.model.impl.AuditEntryImpl
 * @see com.ted.audit.db.model.impl.AuditEntryModelImpl
 * @generated
 */
@ProviderType
public interface AuditEntryModel extends AttachedModel, BaseModel<AuditEntry>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit entry model instance should use the {@link AuditEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this audit entry.
	 *
	 * @return the primary key of this audit entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit entry.
	 *
	 * @param primaryKey the primary key of this audit entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit ID of this audit entry.
	 *
	 * @return the audit ID of this audit entry
	 */
	public long getAuditId();

	/**
	 * Sets the audit ID of this audit entry.
	 *
	 * @param auditId the audit ID of this audit entry
	 */
	public void setAuditId(long auditId);

	/**
	 * Returns the company ID of this audit entry.
	 *
	 * @return the company ID of this audit entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit entry.
	 *
	 * @param companyId the company ID of this audit entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this audit entry.
	 *
	 * @return the group ID of this audit entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this audit entry.
	 *
	 * @param groupId the group ID of this audit entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the fully qualified class name of this audit entry.
	 *
	 * @return the fully qualified class name of this audit entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this audit entry.
	 *
	 * @return the class name ID of this audit entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this audit entry.
	 *
	 * @param classNameId the class name ID of this audit entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this audit entry.
	 *
	 * @return the class pk of this audit entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this audit entry.
	 *
	 * @param classPK the class pk of this audit entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the association class pk of this audit entry.
	 *
	 * @return the association class pk of this audit entry
	 */
	public long getAssociationClassPK();

	/**
	 * Sets the association class pk of this audit entry.
	 *
	 * @param associationClassPK the association class pk of this audit entry
	 */
	public void setAssociationClassPK(long associationClassPK);

	/**
	 * Returns the user ID of this audit entry.
	 *
	 * @return the user ID of this audit entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this audit entry.
	 *
	 * @param userId the user ID of this audit entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audit entry.
	 *
	 * @return the user uuid of this audit entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this audit entry.
	 *
	 * @param userUuid the user uuid of this audit entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this audit entry.
	 *
	 * @return the user name of this audit entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this audit entry.
	 *
	 * @param userName the user name of this audit entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the start date of this audit entry.
	 *
	 * @return the start date of this audit entry
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this audit entry.
	 *
	 * @param startDate the start date of this audit entry
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this audit entry.
	 *
	 * @return the end date of this audit entry
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this audit entry.
	 *
	 * @param endDate the end date of this audit entry
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the action ID of this audit entry.
	 *
	 * @return the action ID of this audit entry
	 */
	public int getActionId();

	/**
	 * Sets the action ID of this audit entry.
	 *
	 * @param actionId the action ID of this audit entry
	 */
	public void setActionId(int actionId);

	/**
	 * Returns the extradata of this audit entry.
	 *
	 * @return the extradata of this audit entry
	 */
	@AutoEscape
	public String getExtradata();

	/**
	 * Sets the extradata of this audit entry.
	 *
	 * @param extradata the extradata of this audit entry
	 */
	public void setExtradata(String extradata);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AuditEntry auditEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AuditEntry> toCacheModel();

	@Override
	public AuditEntry toEscapedModel();

	@Override
	public AuditEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}