/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.ted.lms.model.Course;
import com.ted.lms.model.CourseModel;
import com.ted.lms.model.CourseSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the Course service. Represents a row in the &quot;LMS_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CourseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseImpl
 * @see Course
 * @see CourseModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CourseModelImpl extends BaseModelImpl<Course>
	implements CourseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */
	public static final String TABLE_NAME = "LMS_Course";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "courseId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "parentCourseId", Types.BIGINT },
			{ "groupCreatedId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "friendlyURL", Types.VARCHAR },
			{ "icon", Types.BIGINT },
			{ "registrationStartDate", Types.TIMESTAMP },
			{ "registrationEndDate", Types.TIMESTAMP },
			{ "executionStartDate", Types.TIMESTAMP },
			{ "executionEndDate", Types.TIMESTAMP },
			{ "closed", Types.BOOLEAN },
			{ "maxUsers", Types.INTEGER },
			{ "inscriptionType", Types.BIGINT },
			{ "courseEvalId", Types.BIGINT },
			{ "calificationType", Types.BIGINT },
			{ "welcome", Types.BOOLEAN },
			{ "welcomeSubject", Types.VARCHAR },
			{ "welcomeMsg", Types.CLOB },
			{ "goodbye", Types.BOOLEAN },
			{ "goodbyeSubject", Types.VARCHAR },
			{ "goodbyeMsg", Types.CLOB },
			{ "courseExtraData", Types.VARCHAR },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentCourseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupCreatedId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("friendlyURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("icon", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("registrationStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("registrationEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("executionStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("executionEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("closed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("maxUsers", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("inscriptionType", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("courseEvalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("calificationType", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("welcome", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("welcomeSubject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("welcomeMsg", Types.CLOB);
		TABLE_COLUMNS_MAP.put("goodbye", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("goodbyeSubject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("goodbyeMsg", Types.CLOB);
		TABLE_COLUMNS_MAP.put("courseExtraData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table LMS_Course (uuid_ VARCHAR(75) null,courseId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentCourseId LONG,groupCreatedId LONG,title STRING null,description STRING null,friendlyURL VARCHAR(100) null,icon LONG,registrationStartDate DATE null,registrationEndDate DATE null,executionStartDate DATE null,executionEndDate DATE null,closed BOOLEAN,maxUsers INTEGER,inscriptionType LONG,courseEvalId LONG,calificationType LONG,welcome BOOLEAN,welcomeSubject VARCHAR(75) null,welcomeMsg TEXT null,goodbye BOOLEAN,goodbyeSubject VARCHAR(75) null,goodbyeMsg TEXT null,courseExtraData TEXT null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table LMS_Course";
	public static final String ORDER_BY_JPQL = " ORDER BY course.courseId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LMS_Course.courseId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ted.lms.model.Course"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ted.lms.model.Course"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.ted.lms.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ted.lms.model.Course"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPCREATEDID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long PARENTCOURSEID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long COURSEID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Course toModel(CourseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Course model = new CourseImpl();

		model.setUuid(soapModel.getUuid());
		model.setCourseId(soapModel.getCourseId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setParentCourseId(soapModel.getParentCourseId());
		model.setGroupCreatedId(soapModel.getGroupCreatedId());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setFriendlyURL(soapModel.getFriendlyURL());
		model.setIcon(soapModel.getIcon());
		model.setRegistrationStartDate(soapModel.getRegistrationStartDate());
		model.setRegistrationEndDate(soapModel.getRegistrationEndDate());
		model.setExecutionStartDate(soapModel.getExecutionStartDate());
		model.setExecutionEndDate(soapModel.getExecutionEndDate());
		model.setClosed(soapModel.isClosed());
		model.setMaxUsers(soapModel.getMaxUsers());
		model.setInscriptionType(soapModel.getInscriptionType());
		model.setCourseEvalId(soapModel.getCourseEvalId());
		model.setCalificationType(soapModel.getCalificationType());
		model.setWelcome(soapModel.isWelcome());
		model.setWelcomeSubject(soapModel.getWelcomeSubject());
		model.setWelcomeMsg(soapModel.getWelcomeMsg());
		model.setGoodbye(soapModel.isGoodbye());
		model.setGoodbyeSubject(soapModel.getGoodbyeSubject());
		model.setGoodbyeMsg(soapModel.getGoodbyeMsg());
		model.setCourseExtraData(soapModel.getCourseExtraData());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Course> toModels(CourseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Course> models = new ArrayList<Course>(soapModels.length);

		for (CourseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.ted.lms.service.util.ServiceProps.get(
				"lock.expiration.time.com.ted.lms.model.Course"));

	public CourseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _courseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCourseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _courseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Course.class;
	}

	@Override
	public String getModelClassName() {
		return Course.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("courseId", getCourseId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("parentCourseId", getParentCourseId());
		attributes.put("groupCreatedId", getGroupCreatedId());
		attributes.put("title", getTitle());
		attributes.put("description", getDescription());
		attributes.put("friendlyURL", getFriendlyURL());
		attributes.put("icon", getIcon());
		attributes.put("registrationStartDate", getRegistrationStartDate());
		attributes.put("registrationEndDate", getRegistrationEndDate());
		attributes.put("executionStartDate", getExecutionStartDate());
		attributes.put("executionEndDate", getExecutionEndDate());
		attributes.put("closed", isClosed());
		attributes.put("maxUsers", getMaxUsers());
		attributes.put("inscriptionType", getInscriptionType());
		attributes.put("courseEvalId", getCourseEvalId());
		attributes.put("calificationType", getCalificationType());
		attributes.put("welcome", isWelcome());
		attributes.put("welcomeSubject", getWelcomeSubject());
		attributes.put("welcomeMsg", getWelcomeMsg());
		attributes.put("goodbye", isGoodbye());
		attributes.put("goodbyeSubject", getGoodbyeSubject());
		attributes.put("goodbyeMsg", getGoodbyeMsg());
		attributes.put("courseExtraData", getCourseExtraData());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long courseId = (Long)attributes.get("courseId");

		if (courseId != null) {
			setCourseId(courseId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long parentCourseId = (Long)attributes.get("parentCourseId");

		if (parentCourseId != null) {
			setParentCourseId(parentCourseId);
		}

		Long groupCreatedId = (Long)attributes.get("groupCreatedId");

		if (groupCreatedId != null) {
			setGroupCreatedId(groupCreatedId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String friendlyURL = (String)attributes.get("friendlyURL");

		if (friendlyURL != null) {
			setFriendlyURL(friendlyURL);
		}

		Long icon = (Long)attributes.get("icon");

		if (icon != null) {
			setIcon(icon);
		}

		Date registrationStartDate = (Date)attributes.get(
				"registrationStartDate");

		if (registrationStartDate != null) {
			setRegistrationStartDate(registrationStartDate);
		}

		Date registrationEndDate = (Date)attributes.get("registrationEndDate");

		if (registrationEndDate != null) {
			setRegistrationEndDate(registrationEndDate);
		}

		Date executionStartDate = (Date)attributes.get("executionStartDate");

		if (executionStartDate != null) {
			setExecutionStartDate(executionStartDate);
		}

		Date executionEndDate = (Date)attributes.get("executionEndDate");

		if (executionEndDate != null) {
			setExecutionEndDate(executionEndDate);
		}

		Boolean closed = (Boolean)attributes.get("closed");

		if (closed != null) {
			setClosed(closed);
		}

		Integer maxUsers = (Integer)attributes.get("maxUsers");

		if (maxUsers != null) {
			setMaxUsers(maxUsers);
		}

		Long inscriptionType = (Long)attributes.get("inscriptionType");

		if (inscriptionType != null) {
			setInscriptionType(inscriptionType);
		}

		Long courseEvalId = (Long)attributes.get("courseEvalId");

		if (courseEvalId != null) {
			setCourseEvalId(courseEvalId);
		}

		Long calificationType = (Long)attributes.get("calificationType");

		if (calificationType != null) {
			setCalificationType(calificationType);
		}

		Boolean welcome = (Boolean)attributes.get("welcome");

		if (welcome != null) {
			setWelcome(welcome);
		}

		String welcomeSubject = (String)attributes.get("welcomeSubject");

		if (welcomeSubject != null) {
			setWelcomeSubject(welcomeSubject);
		}

		String welcomeMsg = (String)attributes.get("welcomeMsg");

		if (welcomeMsg != null) {
			setWelcomeMsg(welcomeMsg);
		}

		Boolean goodbye = (Boolean)attributes.get("goodbye");

		if (goodbye != null) {
			setGoodbye(goodbye);
		}

		String goodbyeSubject = (String)attributes.get("goodbyeSubject");

		if (goodbyeSubject != null) {
			setGoodbyeSubject(goodbyeSubject);
		}

		String goodbyeMsg = (String)attributes.get("goodbyeMsg");

		if (goodbyeMsg != null) {
			setGoodbyeMsg(goodbyeMsg);
		}

		String courseExtraData = (String)attributes.get("courseExtraData");

		if (courseExtraData != null) {
			setCourseExtraData(courseExtraData);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCourseId() {
		return _courseId;
	}

	@Override
	public void setCourseId(long courseId) {
		_columnBitmask = -1L;

		_courseId = courseId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getParentCourseId() {
		return _parentCourseId;
	}

	@Override
	public void setParentCourseId(long parentCourseId) {
		_columnBitmask |= PARENTCOURSEID_COLUMN_BITMASK;

		if (!_setOriginalParentCourseId) {
			_setOriginalParentCourseId = true;

			_originalParentCourseId = _parentCourseId;
		}

		_parentCourseId = parentCourseId;
	}

	public long getOriginalParentCourseId() {
		return _originalParentCourseId;
	}

	@JSON
	@Override
	public long getGroupCreatedId() {
		return _groupCreatedId;
	}

	@Override
	public void setGroupCreatedId(long groupCreatedId) {
		_columnBitmask |= GROUPCREATEDID_COLUMN_BITMASK;

		if (!_setOriginalGroupCreatedId) {
			_setOriginalGroupCreatedId = true;

			_originalGroupCreatedId = _groupCreatedId;
		}

		_groupCreatedId = groupCreatedId;
	}

	public long getOriginalGroupCreatedId() {
		return _originalGroupCreatedId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getTitle(), languageId,
			useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(LocalizationUtil.updateLocalization(getTitle(), "Title",
					title, languageId, defaultLanguageId));
		}
		else {
			setTitle(LocalizationUtil.removeLocalization(getTitle(), "Title",
					languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale) {
		if (titleMap == null) {
			return;
		}

		setTitle(LocalizationUtil.updateLocalization(titleMap, getTitle(),
				"Title", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDescription(), languageId,
			useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(String description, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale) {
		if (descriptionMap == null) {
			return;
		}

		setDescription(LocalizationUtil.updateLocalization(descriptionMap,
				getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getFriendlyURL() {
		if (_friendlyURL == null) {
			return "";
		}
		else {
			return _friendlyURL;
		}
	}

	@Override
	public void setFriendlyURL(String friendlyURL) {
		_friendlyURL = friendlyURL;
	}

	@JSON
	@Override
	public long getIcon() {
		return _icon;
	}

	@Override
	public void setIcon(long icon) {
		_icon = icon;
	}

	@JSON
	@Override
	public Date getRegistrationStartDate() {
		return _registrationStartDate;
	}

	@Override
	public void setRegistrationStartDate(Date registrationStartDate) {
		_registrationStartDate = registrationStartDate;
	}

	@JSON
	@Override
	public Date getRegistrationEndDate() {
		return _registrationEndDate;
	}

	@Override
	public void setRegistrationEndDate(Date registrationEndDate) {
		_registrationEndDate = registrationEndDate;
	}

	@JSON
	@Override
	public Date getExecutionStartDate() {
		return _executionStartDate;
	}

	@Override
	public void setExecutionStartDate(Date executionStartDate) {
		_executionStartDate = executionStartDate;
	}

	@JSON
	@Override
	public Date getExecutionEndDate() {
		return _executionEndDate;
	}

	@Override
	public void setExecutionEndDate(Date executionEndDate) {
		_executionEndDate = executionEndDate;
	}

	@JSON
	@Override
	public boolean getClosed() {
		return _closed;
	}

	@JSON
	@Override
	public boolean isClosed() {
		return _closed;
	}

	@Override
	public void setClosed(boolean closed) {
		_closed = closed;
	}

	@JSON
	@Override
	public int getMaxUsers() {
		return _maxUsers;
	}

	@Override
	public void setMaxUsers(int maxUsers) {
		_maxUsers = maxUsers;
	}

	@JSON
	@Override
	public long getInscriptionType() {
		return _inscriptionType;
	}

	@Override
	public void setInscriptionType(long inscriptionType) {
		_inscriptionType = inscriptionType;
	}

	@JSON
	@Override
	public long getCourseEvalId() {
		return _courseEvalId;
	}

	@Override
	public void setCourseEvalId(long courseEvalId) {
		_courseEvalId = courseEvalId;
	}

	@JSON
	@Override
	public long getCalificationType() {
		return _calificationType;
	}

	@Override
	public void setCalificationType(long calificationType) {
		_calificationType = calificationType;
	}

	@JSON
	@Override
	public boolean getWelcome() {
		return _welcome;
	}

	@JSON
	@Override
	public boolean isWelcome() {
		return _welcome;
	}

	@Override
	public void setWelcome(boolean welcome) {
		_welcome = welcome;
	}

	@JSON
	@Override
	public String getWelcomeSubject() {
		if (_welcomeSubject == null) {
			return "";
		}
		else {
			return _welcomeSubject;
		}
	}

	@Override
	public void setWelcomeSubject(String welcomeSubject) {
		_welcomeSubject = welcomeSubject;
	}

	@JSON
	@Override
	public String getWelcomeMsg() {
		if (_welcomeMsg == null) {
			return "";
		}
		else {
			return _welcomeMsg;
		}
	}

	@Override
	public void setWelcomeMsg(String welcomeMsg) {
		_welcomeMsg = welcomeMsg;
	}

	@JSON
	@Override
	public boolean getGoodbye() {
		return _goodbye;
	}

	@JSON
	@Override
	public boolean isGoodbye() {
		return _goodbye;
	}

	@Override
	public void setGoodbye(boolean goodbye) {
		_goodbye = goodbye;
	}

	@JSON
	@Override
	public String getGoodbyeSubject() {
		if (_goodbyeSubject == null) {
			return "";
		}
		else {
			return _goodbyeSubject;
		}
	}

	@Override
	public void setGoodbyeSubject(String goodbyeSubject) {
		_goodbyeSubject = goodbyeSubject;
	}

	@JSON
	@Override
	public String getGoodbyeMsg() {
		if (_goodbyeMsg == null) {
			return "";
		}
		else {
			return _goodbyeMsg;
		}
	}

	@Override
	public void setGoodbyeMsg(String goodbyeMsg) {
		_goodbyeMsg = goodbyeMsg;
	}

	@JSON
	@Override
	public String getCourseExtraData() {
		if (_courseExtraData == null) {
			return "";
		}
		else {
			return _courseExtraData;
		}
	}

	@Override
	public void setCourseExtraData(String courseExtraData) {
		_courseExtraData = courseExtraData;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Course.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Course.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(Course.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(getDescription(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public Course toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Course)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseImpl courseImpl = new CourseImpl();

		courseImpl.setUuid(getUuid());
		courseImpl.setCourseId(getCourseId());
		courseImpl.setGroupId(getGroupId());
		courseImpl.setCompanyId(getCompanyId());
		courseImpl.setUserId(getUserId());
		courseImpl.setUserName(getUserName());
		courseImpl.setCreateDate(getCreateDate());
		courseImpl.setModifiedDate(getModifiedDate());
		courseImpl.setParentCourseId(getParentCourseId());
		courseImpl.setGroupCreatedId(getGroupCreatedId());
		courseImpl.setTitle(getTitle());
		courseImpl.setDescription(getDescription());
		courseImpl.setFriendlyURL(getFriendlyURL());
		courseImpl.setIcon(getIcon());
		courseImpl.setRegistrationStartDate(getRegistrationStartDate());
		courseImpl.setRegistrationEndDate(getRegistrationEndDate());
		courseImpl.setExecutionStartDate(getExecutionStartDate());
		courseImpl.setExecutionEndDate(getExecutionEndDate());
		courseImpl.setClosed(isClosed());
		courseImpl.setMaxUsers(getMaxUsers());
		courseImpl.setInscriptionType(getInscriptionType());
		courseImpl.setCourseEvalId(getCourseEvalId());
		courseImpl.setCalificationType(getCalificationType());
		courseImpl.setWelcome(isWelcome());
		courseImpl.setWelcomeSubject(getWelcomeSubject());
		courseImpl.setWelcomeMsg(getWelcomeMsg());
		courseImpl.setGoodbye(isGoodbye());
		courseImpl.setGoodbyeSubject(getGoodbyeSubject());
		courseImpl.setGoodbyeMsg(getGoodbyeMsg());
		courseImpl.setCourseExtraData(getCourseExtraData());
		courseImpl.setStatus(getStatus());
		courseImpl.setStatusByUserId(getStatusByUserId());
		courseImpl.setStatusByUserName(getStatusByUserName());
		courseImpl.setStatusDate(getStatusDate());

		courseImpl.resetOriginalValues();

		return courseImpl;
	}

	@Override
	public int compareTo(Course course) {
		int value = 0;

		if (getCourseId() < course.getCourseId()) {
			value = -1;
		}
		else if (getCourseId() > course.getCourseId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Course)) {
			return false;
		}

		Course course = (Course)obj;

		long primaryKey = course.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CourseModelImpl courseModelImpl = this;

		courseModelImpl._originalUuid = courseModelImpl._uuid;

		courseModelImpl._originalGroupId = courseModelImpl._groupId;

		courseModelImpl._setOriginalGroupId = false;

		courseModelImpl._originalCompanyId = courseModelImpl._companyId;

		courseModelImpl._setOriginalCompanyId = false;

		courseModelImpl._setModifiedDate = false;

		courseModelImpl._originalParentCourseId = courseModelImpl._parentCourseId;

		courseModelImpl._setOriginalParentCourseId = false;

		courseModelImpl._originalGroupCreatedId = courseModelImpl._groupCreatedId;

		courseModelImpl._setOriginalGroupCreatedId = false;

		courseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Course> toCacheModel() {
		CourseCacheModel courseCacheModel = new CourseCacheModel();

		courseCacheModel.uuid = getUuid();

		String uuid = courseCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			courseCacheModel.uuid = null;
		}

		courseCacheModel.courseId = getCourseId();

		courseCacheModel.groupId = getGroupId();

		courseCacheModel.companyId = getCompanyId();

		courseCacheModel.userId = getUserId();

		courseCacheModel.userName = getUserName();

		String userName = courseCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			courseCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseCacheModel.createDate = createDate.getTime();
		}
		else {
			courseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		courseCacheModel.parentCourseId = getParentCourseId();

		courseCacheModel.groupCreatedId = getGroupCreatedId();

		courseCacheModel.title = getTitle();

		String title = courseCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			courseCacheModel.title = null;
		}

		courseCacheModel.description = getDescription();

		String description = courseCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			courseCacheModel.description = null;
		}

		courseCacheModel.friendlyURL = getFriendlyURL();

		String friendlyURL = courseCacheModel.friendlyURL;

		if ((friendlyURL != null) && (friendlyURL.length() == 0)) {
			courseCacheModel.friendlyURL = null;
		}

		courseCacheModel.icon = getIcon();

		Date registrationStartDate = getRegistrationStartDate();

		if (registrationStartDate != null) {
			courseCacheModel.registrationStartDate = registrationStartDate.getTime();
		}
		else {
			courseCacheModel.registrationStartDate = Long.MIN_VALUE;
		}

		Date registrationEndDate = getRegistrationEndDate();

		if (registrationEndDate != null) {
			courseCacheModel.registrationEndDate = registrationEndDate.getTime();
		}
		else {
			courseCacheModel.registrationEndDate = Long.MIN_VALUE;
		}

		Date executionStartDate = getExecutionStartDate();

		if (executionStartDate != null) {
			courseCacheModel.executionStartDate = executionStartDate.getTime();
		}
		else {
			courseCacheModel.executionStartDate = Long.MIN_VALUE;
		}

		Date executionEndDate = getExecutionEndDate();

		if (executionEndDate != null) {
			courseCacheModel.executionEndDate = executionEndDate.getTime();
		}
		else {
			courseCacheModel.executionEndDate = Long.MIN_VALUE;
		}

		courseCacheModel.closed = isClosed();

		courseCacheModel.maxUsers = getMaxUsers();

		courseCacheModel.inscriptionType = getInscriptionType();

		courseCacheModel.courseEvalId = getCourseEvalId();

		courseCacheModel.calificationType = getCalificationType();

		courseCacheModel.welcome = isWelcome();

		courseCacheModel.welcomeSubject = getWelcomeSubject();

		String welcomeSubject = courseCacheModel.welcomeSubject;

		if ((welcomeSubject != null) && (welcomeSubject.length() == 0)) {
			courseCacheModel.welcomeSubject = null;
		}

		courseCacheModel.welcomeMsg = getWelcomeMsg();

		String welcomeMsg = courseCacheModel.welcomeMsg;

		if ((welcomeMsg != null) && (welcomeMsg.length() == 0)) {
			courseCacheModel.welcomeMsg = null;
		}

		courseCacheModel.goodbye = isGoodbye();

		courseCacheModel.goodbyeSubject = getGoodbyeSubject();

		String goodbyeSubject = courseCacheModel.goodbyeSubject;

		if ((goodbyeSubject != null) && (goodbyeSubject.length() == 0)) {
			courseCacheModel.goodbyeSubject = null;
		}

		courseCacheModel.goodbyeMsg = getGoodbyeMsg();

		String goodbyeMsg = courseCacheModel.goodbyeMsg;

		if ((goodbyeMsg != null) && (goodbyeMsg.length() == 0)) {
			courseCacheModel.goodbyeMsg = null;
		}

		courseCacheModel.courseExtraData = getCourseExtraData();

		String courseExtraData = courseCacheModel.courseExtraData;

		if ((courseExtraData != null) && (courseExtraData.length() == 0)) {
			courseCacheModel.courseExtraData = null;
		}

		courseCacheModel.status = getStatus();

		courseCacheModel.statusByUserId = getStatusByUserId();

		courseCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = courseCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			courseCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			courseCacheModel.statusDate = statusDate.getTime();
		}
		else {
			courseCacheModel.statusDate = Long.MIN_VALUE;
		}

		return courseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(69);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", courseId=");
		sb.append(getCourseId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", parentCourseId=");
		sb.append(getParentCourseId());
		sb.append(", groupCreatedId=");
		sb.append(getGroupCreatedId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", friendlyURL=");
		sb.append(getFriendlyURL());
		sb.append(", icon=");
		sb.append(getIcon());
		sb.append(", registrationStartDate=");
		sb.append(getRegistrationStartDate());
		sb.append(", registrationEndDate=");
		sb.append(getRegistrationEndDate());
		sb.append(", executionStartDate=");
		sb.append(getExecutionStartDate());
		sb.append(", executionEndDate=");
		sb.append(getExecutionEndDate());
		sb.append(", closed=");
		sb.append(isClosed());
		sb.append(", maxUsers=");
		sb.append(getMaxUsers());
		sb.append(", inscriptionType=");
		sb.append(getInscriptionType());
		sb.append(", courseEvalId=");
		sb.append(getCourseEvalId());
		sb.append(", calificationType=");
		sb.append(getCalificationType());
		sb.append(", welcome=");
		sb.append(isWelcome());
		sb.append(", welcomeSubject=");
		sb.append(getWelcomeSubject());
		sb.append(", welcomeMsg=");
		sb.append(getWelcomeMsg());
		sb.append(", goodbye=");
		sb.append(isGoodbye());
		sb.append(", goodbyeSubject=");
		sb.append(getGoodbyeSubject());
		sb.append(", goodbyeMsg=");
		sb.append(getGoodbyeMsg());
		sb.append(", courseExtraData=");
		sb.append(getCourseExtraData());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(106);

		sb.append("<model><model-name>");
		sb.append("com.ted.lms.model.Course");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseId</column-name><column-value><![CDATA[");
		sb.append(getCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentCourseId</column-name><column-value><![CDATA[");
		sb.append(getParentCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupCreatedId</column-name><column-value><![CDATA[");
		sb.append(getGroupCreatedId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>friendlyURL</column-name><column-value><![CDATA[");
		sb.append(getFriendlyURL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>icon</column-name><column-value><![CDATA[");
		sb.append(getIcon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registrationStartDate</column-name><column-value><![CDATA[");
		sb.append(getRegistrationStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registrationEndDate</column-name><column-value><![CDATA[");
		sb.append(getRegistrationEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>executionStartDate</column-name><column-value><![CDATA[");
		sb.append(getExecutionStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>executionEndDate</column-name><column-value><![CDATA[");
		sb.append(getExecutionEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>closed</column-name><column-value><![CDATA[");
		sb.append(isClosed());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxUsers</column-name><column-value><![CDATA[");
		sb.append(getMaxUsers());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inscriptionType</column-name><column-value><![CDATA[");
		sb.append(getInscriptionType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseEvalId</column-name><column-value><![CDATA[");
		sb.append(getCourseEvalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>calificationType</column-name><column-value><![CDATA[");
		sb.append(getCalificationType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>welcome</column-name><column-value><![CDATA[");
		sb.append(isWelcome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>welcomeSubject</column-name><column-value><![CDATA[");
		sb.append(getWelcomeSubject());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>welcomeMsg</column-name><column-value><![CDATA[");
		sb.append(getWelcomeMsg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>goodbye</column-name><column-value><![CDATA[");
		sb.append(isGoodbye());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>goodbyeSubject</column-name><column-value><![CDATA[");
		sb.append(getGoodbyeSubject());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>goodbyeMsg</column-name><column-value><![CDATA[");
		sb.append(getGoodbyeMsg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseExtraData</column-name><column-value><![CDATA[");
		sb.append(getCourseExtraData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Course.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Course.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _courseId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentCourseId;
	private long _originalParentCourseId;
	private boolean _setOriginalParentCourseId;
	private long _groupCreatedId;
	private long _originalGroupCreatedId;
	private boolean _setOriginalGroupCreatedId;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _friendlyURL;
	private long _icon;
	private Date _registrationStartDate;
	private Date _registrationEndDate;
	private Date _executionStartDate;
	private Date _executionEndDate;
	private boolean _closed;
	private int _maxUsers;
	private long _inscriptionType;
	private long _courseEvalId;
	private long _calificationType;
	private boolean _welcome;
	private String _welcomeSubject;
	private String _welcomeMsg;
	private boolean _goodbye;
	private String _goodbyeSubject;
	private String _goodbyeMsg;
	private String _courseExtraData;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private Course _escapedModel;
}