/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import com.ted.lms.model.CourseTypeRelation;
import com.ted.lms.model.CourseTypeRelationModel;
import com.ted.lms.service.persistence.CourseTypeRelationPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CourseTypeRelation service. Represents a row in the &quot;LMS_CourseTypeRelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CourseTypeRelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseTypeRelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseTypeRelationImpl
 * @see CourseTypeRelation
 * @see CourseTypeRelationModel
 * @generated
 */
@ProviderType
public class CourseTypeRelationModelImpl extends BaseModelImpl<CourseTypeRelation>
	implements CourseTypeRelationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course type relation model instance should use the {@link CourseTypeRelation} interface instead.
	 */
	public static final String TABLE_NAME = "LMS_CourseTypeRelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "courseTypeId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("courseTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table LMS_CourseTypeRelation (courseTypeId LONG not null,classNameId LONG not null,classPK LONG not null,primary key (courseTypeId, classNameId, classPK))";
	public static final String TABLE_SQL_DROP = "drop table LMS_CourseTypeRelation";
	public static final String ORDER_BY_JPQL = " ORDER BY courseTypeRelation.id.courseTypeId ASC, courseTypeRelation.id.classNameId ASC, courseTypeRelation.id.classPK ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LMS_CourseTypeRelation.courseTypeId ASC, LMS_CourseTypeRelation.classNameId ASC, LMS_CourseTypeRelation.classPK ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ted.lms.model.CourseTypeRelation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.lms.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ted.lms.model.CourseTypeRelation"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.ted.lms.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ted.lms.model.CourseTypeRelation"),
			true);
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static final long COURSETYPEID_COLUMN_BITMASK = 2L;
	public static final long CLASSPK_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.ted.lms.service.util.ServiceProps.get(
				"lock.expiration.time.com.ted.lms.model.CourseTypeRelation"));

	public CourseTypeRelationModelImpl() {
	}

	@Override
	public CourseTypeRelationPK getPrimaryKey() {
		return new CourseTypeRelationPK(_courseTypeId, _classNameId, _classPK);
	}

	@Override
	public void setPrimaryKey(CourseTypeRelationPK primaryKey) {
		setCourseTypeId(primaryKey.courseTypeId);
		setClassNameId(primaryKey.classNameId);
		setClassPK(primaryKey.classPK);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new CourseTypeRelationPK(_courseTypeId, _classNameId, _classPK);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((CourseTypeRelationPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return CourseTypeRelation.class;
	}

	@Override
	public String getModelClassName() {
		return CourseTypeRelation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("courseTypeId", getCourseTypeId());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long courseTypeId = (Long)attributes.get("courseTypeId");

		if (courseTypeId != null) {
			setCourseTypeId(courseTypeId);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}
	}

	@Override
	public long getCourseTypeId() {
		return _courseTypeId;
	}

	@Override
	public void setCourseTypeId(long courseTypeId) {
		_columnBitmask |= COURSETYPEID_COLUMN_BITMASK;

		if (!_setOriginalCourseTypeId) {
			_setOriginalCourseTypeId = true;

			_originalCourseTypeId = _courseTypeId;
		}

		_courseTypeId = courseTypeId;
	}

	public long getOriginalCourseTypeId() {
		return _originalCourseTypeId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CourseTypeRelation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CourseTypeRelation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseTypeRelationImpl courseTypeRelationImpl = new CourseTypeRelationImpl();

		courseTypeRelationImpl.setCourseTypeId(getCourseTypeId());
		courseTypeRelationImpl.setClassNameId(getClassNameId());
		courseTypeRelationImpl.setClassPK(getClassPK());

		courseTypeRelationImpl.resetOriginalValues();

		return courseTypeRelationImpl;
	}

	@Override
	public int compareTo(CourseTypeRelation courseTypeRelation) {
		CourseTypeRelationPK primaryKey = courseTypeRelation.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CourseTypeRelation)) {
			return false;
		}

		CourseTypeRelation courseTypeRelation = (CourseTypeRelation)obj;

		CourseTypeRelationPK primaryKey = courseTypeRelation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CourseTypeRelationModelImpl courseTypeRelationModelImpl = this;

		courseTypeRelationModelImpl._originalCourseTypeId = courseTypeRelationModelImpl._courseTypeId;

		courseTypeRelationModelImpl._setOriginalCourseTypeId = false;

		courseTypeRelationModelImpl._originalClassNameId = courseTypeRelationModelImpl._classNameId;

		courseTypeRelationModelImpl._setOriginalClassNameId = false;

		courseTypeRelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CourseTypeRelation> toCacheModel() {
		CourseTypeRelationCacheModel courseTypeRelationCacheModel = new CourseTypeRelationCacheModel();

		courseTypeRelationCacheModel.courseTypeRelationPK = getPrimaryKey();

		courseTypeRelationCacheModel.courseTypeId = getCourseTypeId();

		courseTypeRelationCacheModel.classNameId = getClassNameId();

		courseTypeRelationCacheModel.classPK = getClassPK();

		return courseTypeRelationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{courseTypeId=");
		sb.append(getCourseTypeId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.ted.lms.model.CourseTypeRelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>courseTypeId</column-name><column-value><![CDATA[");
		sb.append(getCourseTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CourseTypeRelation.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CourseTypeRelation.class, ModelWrapper.class
		};
	private long _courseTypeId;
	private long _originalCourseTypeId;
	private boolean _setOriginalCourseTypeId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _columnBitmask;
	private CourseTypeRelation _escapedModel;
}