/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.ted.lms.model.ModuleResult;
import com.ted.lms.model.ModuleResultModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the ModuleResult service. Represents a row in the &quot;LMS_ModuleResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ModuleResultModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ModuleResultImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ModuleResultImpl
 * @generated
 */
@ProviderType
public class ModuleResultModelImpl
	extends BaseModelImpl<ModuleResult> implements ModuleResultModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a module result model instance should use the <code>ModuleResult</code> interface instead.
	 */
	public static final String TABLE_NAME = "LMS_ModuleResult";

	public static final Object[][] TABLE_COLUMNS = {
		{"mrId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userModifiedId", Types.BIGINT},
		{"userModifiedName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"moduleId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"result", Types.DOUBLE},
		{"comments", Types.VARCHAR}, {"passed", Types.BOOLEAN},
		{"startDate", Types.TIMESTAMP}, {"passedDate", Types.TIMESTAMP},
		{"extraData", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mrId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userModifiedId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userModifiedName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("moduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("result", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("comments", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("passed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("passedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("extraData", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LMS_ModuleResult (mrId LONG not null primary key,groupId LONG,companyId LONG,userModifiedId LONG,userModifiedName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,moduleId LONG,userId LONG,result DOUBLE,comments TEXT null,passed BOOLEAN,startDate DATE null,passedDate DATE null,extraData TEXT null)";

	public static final String TABLE_SQL_DROP = "drop table LMS_ModuleResult";

	public static final String ORDER_BY_JPQL =
		" ORDER BY moduleResult.mrId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LMS_ModuleResult.mrId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MODULEID_COLUMN_BITMASK = 1L;

	public static final long USERID_COLUMN_BITMASK = 2L;

	public static final long MRID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ModuleResultModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mrId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMrId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mrId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ModuleResult.class;
	}

	@Override
	public String getModelClassName() {
		return ModuleResult.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ModuleResult, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ModuleResult, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ModuleResult, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ModuleResult)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ModuleResult, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ModuleResult, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ModuleResult)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ModuleResult, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ModuleResult, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ModuleResult>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ModuleResult.class.getClassLoader(), ModuleResult.class,
			ModelWrapper.class);

		try {
			Constructor<ModuleResult> constructor =
				(Constructor<ModuleResult>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ModuleResult, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ModuleResult, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ModuleResult, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ModuleResult, Object>>();
		Map<String, BiConsumer<ModuleResult, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ModuleResult, ?>>();

		attributeGetterFunctions.put("mrId", ModuleResult::getMrId);
		attributeSetterBiConsumers.put(
			"mrId", (BiConsumer<ModuleResult, Long>)ModuleResult::setMrId);
		attributeGetterFunctions.put("groupId", ModuleResult::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ModuleResult, Long>)ModuleResult::setGroupId);
		attributeGetterFunctions.put("companyId", ModuleResult::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ModuleResult, Long>)ModuleResult::setCompanyId);
		attributeGetterFunctions.put(
			"userModifiedId", ModuleResult::getUserModifiedId);
		attributeSetterBiConsumers.put(
			"userModifiedId",
			(BiConsumer<ModuleResult, Long>)ModuleResult::setUserModifiedId);
		attributeGetterFunctions.put(
			"userModifiedName", ModuleResult::getUserModifiedName);
		attributeSetterBiConsumers.put(
			"userModifiedName",
			(BiConsumer<ModuleResult, String>)
				ModuleResult::setUserModifiedName);
		attributeGetterFunctions.put("createDate", ModuleResult::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ModuleResult, Date>)ModuleResult::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ModuleResult::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ModuleResult, Date>)ModuleResult::setModifiedDate);
		attributeGetterFunctions.put("moduleId", ModuleResult::getModuleId);
		attributeSetterBiConsumers.put(
			"moduleId",
			(BiConsumer<ModuleResult, Long>)ModuleResult::setModuleId);
		attributeGetterFunctions.put("userId", ModuleResult::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ModuleResult, Long>)ModuleResult::setUserId);
		attributeGetterFunctions.put("result", ModuleResult::getResult);
		attributeSetterBiConsumers.put(
			"result",
			(BiConsumer<ModuleResult, Double>)ModuleResult::setResult);
		attributeGetterFunctions.put("comments", ModuleResult::getComments);
		attributeSetterBiConsumers.put(
			"comments",
			(BiConsumer<ModuleResult, String>)ModuleResult::setComments);
		attributeGetterFunctions.put("passed", ModuleResult::getPassed);
		attributeSetterBiConsumers.put(
			"passed",
			(BiConsumer<ModuleResult, Boolean>)ModuleResult::setPassed);
		attributeGetterFunctions.put("startDate", ModuleResult::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<ModuleResult, Date>)ModuleResult::setStartDate);
		attributeGetterFunctions.put("passedDate", ModuleResult::getPassedDate);
		attributeSetterBiConsumers.put(
			"passedDate",
			(BiConsumer<ModuleResult, Date>)ModuleResult::setPassedDate);
		attributeGetterFunctions.put("extraData", ModuleResult::getExtraData);
		attributeSetterBiConsumers.put(
			"extraData",
			(BiConsumer<ModuleResult, String>)ModuleResult::setExtraData);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMrId() {
		return _mrId;
	}

	@Override
	public void setMrId(long mrId) {
		_mrId = mrId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserModifiedId() {
		return _userModifiedId;
	}

	@Override
	public void setUserModifiedId(long userModifiedId) {
		_userModifiedId = userModifiedId;
	}

	@Override
	public String getUserModifiedName() {
		if (_userModifiedName == null) {
			return "";
		}
		else {
			return _userModifiedName;
		}
	}

	@Override
	public void setUserModifiedName(String userModifiedName) {
		_userModifiedName = userModifiedName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getModuleId() {
		return _moduleId;
	}

	@Override
	public void setModuleId(long moduleId) {
		_columnBitmask |= MODULEID_COLUMN_BITMASK;

		if (!_setOriginalModuleId) {
			_setOriginalModuleId = true;

			_originalModuleId = _moduleId;
		}

		_moduleId = moduleId;
	}

	public long getOriginalModuleId() {
		return _originalModuleId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public double getResult() {
		return _result;
	}

	@Override
	public void setResult(double result) {
		_result = result;
	}

	@Override
	public String getComments() {
		if (_comments == null) {
			return "";
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		_comments = comments;
	}

	@Override
	public boolean getPassed() {
		return _passed;
	}

	@Override
	public boolean isPassed() {
		return _passed;
	}

	@Override
	public void setPassed(boolean passed) {
		_passed = passed;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getPassedDate() {
		return _passedDate;
	}

	@Override
	public void setPassedDate(Date passedDate) {
		_passedDate = passedDate;
	}

	@Override
	public String getExtraData() {
		if (_extraData == null) {
			return "";
		}
		else {
			return _extraData;
		}
	}

	@Override
	public void setExtraData(String extraData) {
		_extraData = extraData;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ModuleResult.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ModuleResult toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ModuleResult>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ModuleResultImpl moduleResultImpl = new ModuleResultImpl();

		moduleResultImpl.setMrId(getMrId());
		moduleResultImpl.setGroupId(getGroupId());
		moduleResultImpl.setCompanyId(getCompanyId());
		moduleResultImpl.setUserModifiedId(getUserModifiedId());
		moduleResultImpl.setUserModifiedName(getUserModifiedName());
		moduleResultImpl.setCreateDate(getCreateDate());
		moduleResultImpl.setModifiedDate(getModifiedDate());
		moduleResultImpl.setModuleId(getModuleId());
		moduleResultImpl.setUserId(getUserId());
		moduleResultImpl.setResult(getResult());
		moduleResultImpl.setComments(getComments());
		moduleResultImpl.setPassed(isPassed());
		moduleResultImpl.setStartDate(getStartDate());
		moduleResultImpl.setPassedDate(getPassedDate());
		moduleResultImpl.setExtraData(getExtraData());

		moduleResultImpl.resetOriginalValues();

		return moduleResultImpl;
	}

	@Override
	public int compareTo(ModuleResult moduleResult) {
		long primaryKey = moduleResult.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ModuleResult)) {
			return false;
		}

		ModuleResult moduleResult = (ModuleResult)obj;

		long primaryKey = moduleResult.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ModuleResultModelImpl moduleResultModelImpl = this;

		moduleResultModelImpl._setModifiedDate = false;

		moduleResultModelImpl._originalModuleId =
			moduleResultModelImpl._moduleId;

		moduleResultModelImpl._setOriginalModuleId = false;

		moduleResultModelImpl._originalUserId = moduleResultModelImpl._userId;

		moduleResultModelImpl._setOriginalUserId = false;

		moduleResultModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ModuleResult> toCacheModel() {
		ModuleResultCacheModel moduleResultCacheModel =
			new ModuleResultCacheModel();

		moduleResultCacheModel.mrId = getMrId();

		moduleResultCacheModel.groupId = getGroupId();

		moduleResultCacheModel.companyId = getCompanyId();

		moduleResultCacheModel.userModifiedId = getUserModifiedId();

		moduleResultCacheModel.userModifiedName = getUserModifiedName();

		String userModifiedName = moduleResultCacheModel.userModifiedName;

		if ((userModifiedName != null) && (userModifiedName.length() == 0)) {
			moduleResultCacheModel.userModifiedName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			moduleResultCacheModel.createDate = createDate.getTime();
		}
		else {
			moduleResultCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			moduleResultCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			moduleResultCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		moduleResultCacheModel.moduleId = getModuleId();

		moduleResultCacheModel.userId = getUserId();

		moduleResultCacheModel.result = getResult();

		moduleResultCacheModel.comments = getComments();

		String comments = moduleResultCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			moduleResultCacheModel.comments = null;
		}

		moduleResultCacheModel.passed = isPassed();

		Date startDate = getStartDate();

		if (startDate != null) {
			moduleResultCacheModel.startDate = startDate.getTime();
		}
		else {
			moduleResultCacheModel.startDate = Long.MIN_VALUE;
		}

		Date passedDate = getPassedDate();

		if (passedDate != null) {
			moduleResultCacheModel.passedDate = passedDate.getTime();
		}
		else {
			moduleResultCacheModel.passedDate = Long.MIN_VALUE;
		}

		moduleResultCacheModel.extraData = getExtraData();

		String extraData = moduleResultCacheModel.extraData;

		if ((extraData != null) && (extraData.length() == 0)) {
			moduleResultCacheModel.extraData = null;
		}

		return moduleResultCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ModuleResult, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ModuleResult, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ModuleResult, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ModuleResult)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ModuleResult, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ModuleResult, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ModuleResult, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ModuleResult)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ModuleResult>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mrId;
	private long _groupId;
	private long _companyId;
	private long _userModifiedId;
	private String _userModifiedName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _moduleId;
	private long _originalModuleId;
	private boolean _setOriginalModuleId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private double _result;
	private String _comments;
	private boolean _passed;
	private Date _startDate;
	private Date _passedDate;
	private String _extraData;
	private long _columnBitmask;
	private ModuleResult _escapedModel;

}