/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.lms.learning.activity.question.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Question service. Represents a row in the &quot;qu_Question&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ted.lms.learning.activity.question.model.impl.QuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ted.lms.learning.activity.question.model.impl.QuestionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Question
 * @see com.ted.lms.learning.activity.question.model.impl.QuestionImpl
 * @see com.ted.lms.learning.activity.question.model.impl.QuestionModelImpl
 * @generated
 */
@ProviderType
public interface QuestionModel extends BaseModel<Question>, GroupedModel,
	LocalizedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question model instance should use the {@link Question} interface instead.
	 */

	/**
	 * Returns the primary key of this question.
	 *
	 * @return the primary key of this question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question.
	 *
	 * @param primaryKey the primary key of this question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this question.
	 *
	 * @return the uuid of this question
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this question.
	 *
	 * @param uuid the uuid of this question
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the question ID of this question.
	 *
	 * @return the question ID of this question
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this question.
	 *
	 * @param questionId the question ID of this question
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the group ID of this question.
	 *
	 * @return the group ID of this question
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this question.
	 *
	 * @param groupId the group ID of this question
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this question.
	 *
	 * @return the company ID of this question
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this question.
	 *
	 * @param companyId the company ID of this question
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this question.
	 *
	 * @return the user ID of this question
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this question.
	 *
	 * @param userId the user ID of this question
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this question.
	 *
	 * @return the user uuid of this question
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this question.
	 *
	 * @param userUuid the user uuid of this question
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this question.
	 *
	 * @return the user name of this question
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this question.
	 *
	 * @param userName the user name of this question
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this question.
	 *
	 * @return the create date of this question
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this question.
	 *
	 * @param createDate the create date of this question
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this question.
	 *
	 * @return the modified date of this question
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this question.
	 *
	 * @param modifiedDate the modified date of this question
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the act ID of this question.
	 *
	 * @return the act ID of this question
	 */
	public long getActId();

	/**
	 * Sets the act ID of this question.
	 *
	 * @param actId the act ID of this question
	 */
	public void setActId(long actId);

	/**
	 * Returns the text of this question.
	 *
	 * @return the text of this question
	 */
	public String getText();

	/**
	 * Returns the localized text of this question in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized text of this question
	 */
	@AutoEscape
	public String getText(Locale locale);

	/**
	 * Returns the localized text of this question in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized text of this question. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getText(Locale locale, boolean useDefault);

	/**
	 * Returns the localized text of this question in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized text of this question
	 */
	@AutoEscape
	public String getText(String languageId);

	/**
	 * Returns the localized text of this question in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized text of this question
	 */
	@AutoEscape
	public String getText(String languageId, boolean useDefault);

	@AutoEscape
	public String getTextCurrentLanguageId();

	@AutoEscape
	public String getTextCurrentValue();

	/**
	 * Returns a map of the locales and localized texts of this question.
	 *
	 * @return the locales and localized texts of this question
	 */
	public Map<Locale, String> getTextMap();

	/**
	 * Sets the text of this question.
	 *
	 * @param text the text of this question
	 */
	public void setText(String text);

	/**
	 * Sets the localized text of this question in the language.
	 *
	 * @param text the localized text of this question
	 * @param locale the locale of the language
	 */
	public void setText(String text, Locale locale);

	/**
	 * Sets the localized text of this question in the language, and sets the default locale.
	 *
	 * @param text the localized text of this question
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setText(String text, Locale locale, Locale defaultLocale);

	public void setTextCurrentLanguageId(String languageId);

	/**
	 * Sets the localized texts of this question from the map of locales and localized texts.
	 *
	 * @param textMap the locales and localized texts of this question
	 */
	public void setTextMap(Map<Locale, String> textMap);

	/**
	 * Sets the localized texts of this question from the map of locales and localized texts, and sets the default locale.
	 *
	 * @param textMap the locales and localized texts of this question
	 * @param defaultLocale the default locale
	 */
	public void setTextMap(Map<Locale, String> textMap, Locale defaultLocale);

	/**
	 * Returns the question type of this question.
	 *
	 * @return the question type of this question
	 */
	public long getQuestionType();

	/**
	 * Sets the question type of this question.
	 *
	 * @param questionType the question type of this question
	 */
	public void setQuestionType(long questionType);

	/**
	 * Returns the active of this question.
	 *
	 * @return the active of this question
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this question is active.
	 *
	 * @return <code>true</code> if this question is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this question is active.
	 *
	 * @param active the active of this question
	 */
	public void setActive(boolean active);

	/**
	 * Returns the weight of this question.
	 *
	 * @return the weight of this question
	 */
	public long getWeight();

	/**
	 * Sets the weight of this question.
	 *
	 * @param weight the weight of this question
	 */
	public void setWeight(long weight);

	/**
	 * Returns the penalize of this question.
	 *
	 * @return the penalize of this question
	 */
	public boolean getPenalize();

	/**
	 * Returns <code>true</code> if this question is penalize.
	 *
	 * @return <code>true</code> if this question is penalize; <code>false</code> otherwise
	 */
	public boolean isPenalize();

	/**
	 * Sets whether this question is penalize.
	 *
	 * @param penalize the penalize of this question
	 */
	public void setPenalize(boolean penalize);

	/**
	 * Returns the extra content of this question.
	 *
	 * @return the extra content of this question
	 */
	@AutoEscape
	public String getExtraContent();

	/**
	 * Sets the extra content of this question.
	 *
	 * @param extraContent the extra content of this question
	 */
	public void setExtraContent(String extraContent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(Question question);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Question> toCacheModel();

	@Override
	public Question toEscapedModel();

	@Override
	public Question toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}