/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.prerequisite.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import com.ted.prerequisite.model.PrerequisiteRelation;
import com.ted.prerequisite.model.PrerequisiteRelationModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the PrerequisiteRelation service. Represents a row in the &quot;pre_PrerequisiteRelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PrerequisiteRelationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrerequisiteRelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PrerequisiteRelationImpl
 * @generated
 */
@ProviderType
public class PrerequisiteRelationModelImpl
	extends BaseModelImpl<PrerequisiteRelation>
	implements PrerequisiteRelationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prerequisite relation model instance should use the <code>PrerequisiteRelation</code> interface instead.
	 */
	public static final String TABLE_NAME = "pre_PrerequisiteRelation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"prerequisiteRelationId", Types.BIGINT},
		{"classNamePrerequisiteId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"extraData", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prerequisiteRelationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNamePrerequisiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("extraData", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pre_PrerequisiteRelation (uuid_ VARCHAR(75) null,prerequisiteRelationId LONG not null primary key,classNamePrerequisiteId LONG,classNameId LONG,classPK LONG,extraData VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table pre_PrerequisiteRelation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY prerequisiteRelation.prerequisiteRelationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pre_PrerequisiteRelation.prerequisiteRelationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long CLASSNAMEPREREQUISITEID_COLUMN_BITMASK = 2L;

	public static final long CLASSPK_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long PREREQUISITERELATIONID_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public PrerequisiteRelationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prerequisiteRelationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPrerequisiteRelationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prerequisiteRelationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PrerequisiteRelation.class;
	}

	@Override
	public String getModelClassName() {
		return PrerequisiteRelation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PrerequisiteRelation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PrerequisiteRelation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PrerequisiteRelation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PrerequisiteRelation)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PrerequisiteRelation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PrerequisiteRelation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PrerequisiteRelation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PrerequisiteRelation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PrerequisiteRelation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PrerequisiteRelation>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PrerequisiteRelation.class.getClassLoader(),
			PrerequisiteRelation.class, ModelWrapper.class);

		try {
			Constructor<PrerequisiteRelation> constructor =
				(Constructor<PrerequisiteRelation>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<PrerequisiteRelation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PrerequisiteRelation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PrerequisiteRelation, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PrerequisiteRelation, Object>>();
		Map<String, BiConsumer<PrerequisiteRelation, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<PrerequisiteRelation, ?>>();

		attributeGetterFunctions.put("uuid", PrerequisiteRelation::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PrerequisiteRelation, String>)
				PrerequisiteRelation::setUuid);
		attributeGetterFunctions.put(
			"prerequisiteRelationId",
			PrerequisiteRelation::getPrerequisiteRelationId);
		attributeSetterBiConsumers.put(
			"prerequisiteRelationId",
			(BiConsumer<PrerequisiteRelation, Long>)
				PrerequisiteRelation::setPrerequisiteRelationId);
		attributeGetterFunctions.put(
			"classNamePrerequisiteId",
			PrerequisiteRelation::getClassNamePrerequisiteId);
		attributeSetterBiConsumers.put(
			"classNamePrerequisiteId",
			(BiConsumer<PrerequisiteRelation, Long>)
				PrerequisiteRelation::setClassNamePrerequisiteId);
		attributeGetterFunctions.put(
			"classNameId", PrerequisiteRelation::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<PrerequisiteRelation, Long>)
				PrerequisiteRelation::setClassNameId);
		attributeGetterFunctions.put(
			"classPK", PrerequisiteRelation::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<PrerequisiteRelation, Long>)
				PrerequisiteRelation::setClassPK);
		attributeGetterFunctions.put(
			"extraData", PrerequisiteRelation::getExtraData);
		attributeSetterBiConsumers.put(
			"extraData",
			(BiConsumer<PrerequisiteRelation, String>)
				PrerequisiteRelation::setExtraData);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getPrerequisiteRelationId() {
		return _prerequisiteRelationId;
	}

	@Override
	public void setPrerequisiteRelationId(long prerequisiteRelationId) {
		_prerequisiteRelationId = prerequisiteRelationId;
	}

	@Override
	public long getClassNamePrerequisiteId() {
		return _classNamePrerequisiteId;
	}

	@Override
	public void setClassNamePrerequisiteId(long classNamePrerequisiteId) {
		_columnBitmask |= CLASSNAMEPREREQUISITEID_COLUMN_BITMASK;

		if (!_setOriginalClassNamePrerequisiteId) {
			_setOriginalClassNamePrerequisiteId = true;

			_originalClassNamePrerequisiteId = _classNamePrerequisiteId;
		}

		_classNamePrerequisiteId = classNamePrerequisiteId;
	}

	public long getOriginalClassNamePrerequisiteId() {
		return _originalClassNamePrerequisiteId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@Override
	public String getExtraData() {
		if (_extraData == null) {
			return "";
		}
		else {
			return _extraData;
		}
	}

	@Override
	public void setExtraData(String extraData) {
		_extraData = extraData;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PrerequisiteRelation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PrerequisiteRelation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrerequisiteRelationImpl prerequisiteRelationImpl =
			new PrerequisiteRelationImpl();

		prerequisiteRelationImpl.setUuid(getUuid());
		prerequisiteRelationImpl.setPrerequisiteRelationId(
			getPrerequisiteRelationId());
		prerequisiteRelationImpl.setClassNamePrerequisiteId(
			getClassNamePrerequisiteId());
		prerequisiteRelationImpl.setClassNameId(getClassNameId());
		prerequisiteRelationImpl.setClassPK(getClassPK());
		prerequisiteRelationImpl.setExtraData(getExtraData());

		prerequisiteRelationImpl.resetOriginalValues();

		return prerequisiteRelationImpl;
	}

	@Override
	public int compareTo(PrerequisiteRelation prerequisiteRelation) {
		long primaryKey = prerequisiteRelation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PrerequisiteRelation)) {
			return false;
		}

		PrerequisiteRelation prerequisiteRelation = (PrerequisiteRelation)obj;

		long primaryKey = prerequisiteRelation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		PrerequisiteRelationModelImpl prerequisiteRelationModelImpl = this;

		prerequisiteRelationModelImpl._originalUuid =
			prerequisiteRelationModelImpl._uuid;

		prerequisiteRelationModelImpl._originalClassNamePrerequisiteId =
			prerequisiteRelationModelImpl._classNamePrerequisiteId;

		prerequisiteRelationModelImpl._setOriginalClassNamePrerequisiteId =
			false;

		prerequisiteRelationModelImpl._originalClassNameId =
			prerequisiteRelationModelImpl._classNameId;

		prerequisiteRelationModelImpl._setOriginalClassNameId = false;

		prerequisiteRelationModelImpl._originalClassPK =
			prerequisiteRelationModelImpl._classPK;

		prerequisiteRelationModelImpl._setOriginalClassPK = false;

		prerequisiteRelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PrerequisiteRelation> toCacheModel() {
		PrerequisiteRelationCacheModel prerequisiteRelationCacheModel =
			new PrerequisiteRelationCacheModel();

		prerequisiteRelationCacheModel.uuid = getUuid();

		String uuid = prerequisiteRelationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			prerequisiteRelationCacheModel.uuid = null;
		}

		prerequisiteRelationCacheModel.prerequisiteRelationId =
			getPrerequisiteRelationId();

		prerequisiteRelationCacheModel.classNamePrerequisiteId =
			getClassNamePrerequisiteId();

		prerequisiteRelationCacheModel.classNameId = getClassNameId();

		prerequisiteRelationCacheModel.classPK = getClassPK();

		prerequisiteRelationCacheModel.extraData = getExtraData();

		String extraData = prerequisiteRelationCacheModel.extraData;

		if ((extraData != null) && (extraData.length() == 0)) {
			prerequisiteRelationCacheModel.extraData = null;
		}

		return prerequisiteRelationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PrerequisiteRelation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PrerequisiteRelation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PrerequisiteRelation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((PrerequisiteRelation)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PrerequisiteRelation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PrerequisiteRelation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PrerequisiteRelation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((PrerequisiteRelation)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, PrerequisiteRelation>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _prerequisiteRelationId;
	private long _classNamePrerequisiteId;
	private long _originalClassNamePrerequisiteId;
	private boolean _setOriginalClassNamePrerequisiteId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _extraData;
	private long _columnBitmask;
	private PrerequisiteRelation _escapedModel;

}