/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ted.prerequisite.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import com.ted.prerequisite.model.PrerequisiteRelation;
import com.ted.prerequisite.model.PrerequisiteRelationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PrerequisiteRelation service. Represents a row in the &quot;pre_PrerequisiteRelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PrerequisiteRelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrerequisiteRelationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PrerequisiteRelationImpl
 * @see PrerequisiteRelation
 * @see PrerequisiteRelationModel
 * @generated
 */
@ProviderType
public class PrerequisiteRelationModelImpl extends BaseModelImpl<PrerequisiteRelation>
	implements PrerequisiteRelationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prerequisite relation model instance should use the {@link PrerequisiteRelation} interface instead.
	 */
	public static final String TABLE_NAME = "pre_PrerequisiteRelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "prerequisiteRelationId", Types.BIGINT },
			{ "classNamePrerequisiteId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "extraData", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prerequisiteRelationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNamePrerequisiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("extraData", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table pre_PrerequisiteRelation (uuid_ VARCHAR(75) null,prerequisiteRelationId LONG not null primary key,classNamePrerequisiteId LONG,classNameId LONG,classPK LONG,extraData VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table pre_PrerequisiteRelation";
	public static final String ORDER_BY_JPQL = " ORDER BY prerequisiteRelation.prerequisiteRelationId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY pre_PrerequisiteRelation.prerequisiteRelationId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.prerequisite.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ted.prerequisite.model.PrerequisiteRelation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.ted.prerequisite.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ted.prerequisite.model.PrerequisiteRelation"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.ted.prerequisite.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ted.prerequisite.model.PrerequisiteRelation"),
			true);
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static final long CLASSNAMEPREREQUISITEID_COLUMN_BITMASK = 2L;
	public static final long CLASSPK_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long PREREQUISITERELATIONID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.ted.prerequisite.service.util.ServiceProps.get(
				"lock.expiration.time.com.ted.prerequisite.model.PrerequisiteRelation"));

	public PrerequisiteRelationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prerequisiteRelationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPrerequisiteRelationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prerequisiteRelationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PrerequisiteRelation.class;
	}

	@Override
	public String getModelClassName() {
		return PrerequisiteRelation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("prerequisiteRelationId", getPrerequisiteRelationId());
		attributes.put("classNamePrerequisiteId", getClassNamePrerequisiteId());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("extraData", getExtraData());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long prerequisiteRelationId = (Long)attributes.get(
				"prerequisiteRelationId");

		if (prerequisiteRelationId != null) {
			setPrerequisiteRelationId(prerequisiteRelationId);
		}

		Long classNamePrerequisiteId = (Long)attributes.get(
				"classNamePrerequisiteId");

		if (classNamePrerequisiteId != null) {
			setClassNamePrerequisiteId(classNamePrerequisiteId);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		String extraData = (String)attributes.get("extraData");

		if (extraData != null) {
			setExtraData(extraData);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getPrerequisiteRelationId() {
		return _prerequisiteRelationId;
	}

	@Override
	public void setPrerequisiteRelationId(long prerequisiteRelationId) {
		_prerequisiteRelationId = prerequisiteRelationId;
	}

	@Override
	public long getClassNamePrerequisiteId() {
		return _classNamePrerequisiteId;
	}

	@Override
	public void setClassNamePrerequisiteId(long classNamePrerequisiteId) {
		_columnBitmask |= CLASSNAMEPREREQUISITEID_COLUMN_BITMASK;

		if (!_setOriginalClassNamePrerequisiteId) {
			_setOriginalClassNamePrerequisiteId = true;

			_originalClassNamePrerequisiteId = _classNamePrerequisiteId;
		}

		_classNamePrerequisiteId = classNamePrerequisiteId;
	}

	public long getOriginalClassNamePrerequisiteId() {
		return _originalClassNamePrerequisiteId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@Override
	public String getExtraData() {
		if (_extraData == null) {
			return "";
		}
		else {
			return _extraData;
		}
	}

	@Override
	public void setExtraData(String extraData) {
		_extraData = extraData;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PrerequisiteRelation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PrerequisiteRelation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PrerequisiteRelation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrerequisiteRelationImpl prerequisiteRelationImpl = new PrerequisiteRelationImpl();

		prerequisiteRelationImpl.setUuid(getUuid());
		prerequisiteRelationImpl.setPrerequisiteRelationId(getPrerequisiteRelationId());
		prerequisiteRelationImpl.setClassNamePrerequisiteId(getClassNamePrerequisiteId());
		prerequisiteRelationImpl.setClassNameId(getClassNameId());
		prerequisiteRelationImpl.setClassPK(getClassPK());
		prerequisiteRelationImpl.setExtraData(getExtraData());

		prerequisiteRelationImpl.resetOriginalValues();

		return prerequisiteRelationImpl;
	}

	@Override
	public int compareTo(PrerequisiteRelation prerequisiteRelation) {
		long primaryKey = prerequisiteRelation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PrerequisiteRelation)) {
			return false;
		}

		PrerequisiteRelation prerequisiteRelation = (PrerequisiteRelation)obj;

		long primaryKey = prerequisiteRelation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PrerequisiteRelationModelImpl prerequisiteRelationModelImpl = this;

		prerequisiteRelationModelImpl._originalUuid = prerequisiteRelationModelImpl._uuid;

		prerequisiteRelationModelImpl._originalClassNamePrerequisiteId = prerequisiteRelationModelImpl._classNamePrerequisiteId;

		prerequisiteRelationModelImpl._setOriginalClassNamePrerequisiteId = false;

		prerequisiteRelationModelImpl._originalClassNameId = prerequisiteRelationModelImpl._classNameId;

		prerequisiteRelationModelImpl._setOriginalClassNameId = false;

		prerequisiteRelationModelImpl._originalClassPK = prerequisiteRelationModelImpl._classPK;

		prerequisiteRelationModelImpl._setOriginalClassPK = false;

		prerequisiteRelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PrerequisiteRelation> toCacheModel() {
		PrerequisiteRelationCacheModel prerequisiteRelationCacheModel = new PrerequisiteRelationCacheModel();

		prerequisiteRelationCacheModel.uuid = getUuid();

		String uuid = prerequisiteRelationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			prerequisiteRelationCacheModel.uuid = null;
		}

		prerequisiteRelationCacheModel.prerequisiteRelationId = getPrerequisiteRelationId();

		prerequisiteRelationCacheModel.classNamePrerequisiteId = getClassNamePrerequisiteId();

		prerequisiteRelationCacheModel.classNameId = getClassNameId();

		prerequisiteRelationCacheModel.classPK = getClassPK();

		prerequisiteRelationCacheModel.extraData = getExtraData();

		String extraData = prerequisiteRelationCacheModel.extraData;

		if ((extraData != null) && (extraData.length() == 0)) {
			prerequisiteRelationCacheModel.extraData = null;
		}

		return prerequisiteRelationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", prerequisiteRelationId=");
		sb.append(getPrerequisiteRelationId());
		sb.append(", classNamePrerequisiteId=");
		sb.append(getClassNamePrerequisiteId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", extraData=");
		sb.append(getExtraData());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.ted.prerequisite.model.PrerequisiteRelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prerequisiteRelationId</column-name><column-value><![CDATA[");
		sb.append(getPrerequisiteRelationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNamePrerequisiteId</column-name><column-value><![CDATA[");
		sb.append(getClassNamePrerequisiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extraData</column-name><column-value><![CDATA[");
		sb.append(getExtraData());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = PrerequisiteRelation.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			PrerequisiteRelation.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _prerequisiteRelationId;
	private long _classNamePrerequisiteId;
	private long _originalClassNamePrerequisiteId;
	private boolean _setOriginalClassNamePrerequisiteId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _extraData;
	private long _columnBitmask;
	private PrerequisiteRelation _escapedModel;
}